### ISSUE TITLE
XVim2 not working w/ XCode Version 9.2 (9C40b)

### ISSUE THREAD

**Issue by seratonic** [XVimProject/XVim2#102]
I went through the process of updating Xcode, signing it, building XVim2 and re-launching Xcode.  No vim emulation.

Please advise.

**Comment by micartu** [comment]
the same problem :(

**Comment by ryantstone** [comment]
I've hit the same problem but @heefan suggested re-code signing and I was able to get it running again with a fresh code sign.

**Comment by seratonic** [comment]
so you code-signed 9.2 twice ryantstone ?

**Comment by heefan** [comment]
@seratonic , you may refer to the two threads, #86  #97 .
The steps are the followings, 

    CodeSign Xcode
    Pull from one of the PRs branches
    make uninstall to clear you had
    make to build XVim2 again
    Restart Xcode

I removed the code sign certificate, and redo code sign Xcode  for new Xcode
(or, you can create another code sign name with new Xcode if you have multiple Xcode)
and remove and re-install xvim2. 
Good luck.

**Comment by seratonic** [comment]
Thanks for the help heefan.  I just followed your steps and am back in action.  All is working.  :)
