### ISSUE TITLE
'd' not working for Xcode  9.2 (9C40b)

### ISSUE THREAD

**Issue by al03** [XVimProject/XVim2#103]
At visual mode 'd' not working.

**Comment by antmd** [comment]
Please pull the latest `master`, make, and try again.

**Comment by yingmu52** [comment]
`** BUILD SUCCEEDED **`, relaunched, not working.

**Comment by mplorentz** [comment]
Are you running into the same issue described in #66 or #117?

**Comment by pebble8888** [comment]
fixed.
