### ISSUE TITLE
Add support for Xcode 9.3

### ISSUE THREAD

**Issue by dan-zheng** [XVimProject/XVim2#108]
I tried installing XVim2 for the new Xcode 9.3 beta but couldn't get it to work.

I followed these steps:
 - Codesign Xcode 9.3 beta and `xcode-select -s /Applications/Xcode-beta.app/`
 - Clone XVim2 and run `make`
 - Open Xcode and accept "Load Bundle", relaunch Xcode

I tried adding the new Xcode 9.3 UUID (`8CC8AD71-C38D-4C1A-A34B-DC78BCE76F57`) to `XVim2/Info.plist` to no avail.
I tried re-codesigning Xcode, uninstalling and reinstalling XVim2, also to no avail.

Am I missing something? Did anyone else get it to work?

**Comment by mayqiyue** [comment]
+1

**Comment by BOOLRon** [comment]
+1

**Comment by Granfalloner** [comment]
+1

**Comment by Mmmmabury** [comment]
+1

**Comment by ivmos** [comment]
Confirmed it simply does not work with 9.3 yet?

**Comment by yixiang** [comment]
Confirmed that XVim2 doesn't work in Xcode 9.3 beta 4.

Error:

```
2018-03-13 15:16:07.994250-0700 Xcode[82767:1979805] Calling IOPPFGetProperty thermally_optimized_xcode!
2018-03-13 15:16:09.374919-0700 Xcode[82767:1979805] [MT] PluginLoading: Required plug-in compatibility UUID 8CC8AD71-C38D-4C1A-A34B-DC78BCE76F57 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2018-03-13 15:16:09.883101-0700 Xcode[82767:1979910] Calling IOPPFGetProperty simulator_utility_clamp!
2018-03-13 15:16:10.962622-0700 Xcode[82767:1979889] NSURLConnection finished with error - code -1100
2018-03-13 15:16:12.225143-0700 GPUToolsAgent[82773:1980038] Mac Agent inited !!!
2018-03-13 15:16:42.412346-0700 Xcode[82767:1979805] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-14136.3/IDEKit/Extension/SourceEditor/IDESourceEditorExtension.m:114
Details:  Built-in source editor extension 'com.apple.dt.XcodeBuiltInExtensions' was not located within 30 seconds.
Object:   <IDESourceEditorExtension>
Method:   +_verifyBuiltInSourceEditorExtensionsFound
Thread:   <NSThread: 0x10d500000>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-03-13 15:16:42.412432-0700 Xcode[82767:1979805] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-14136.3/IDEKit/Extension/SourceEditor/IDESourceEditorExtension.m:118
Details:  Built-in source editor extension 'com.apple.dt.XCDocumenter.XCDocumenterExtension' was not located within 30 seconds.
Object:   <IDESourceEditorExtension>
Method:   +_verifyBuiltInSourceEditorExtensionsFound
Thread:   <NSThread: 0x10d500000>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2018-03-13 15:18:11.467550-0700 Xcode[82767:1979805] MessageTracer: Falling back to default whitelist
```

Note that although it complains about:
```
Required plug-in compatibility UUID 8CC8AD71-C38D-4C1A-A34B-DC78BCE76F57 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin' not present in DVTPlugInCompatibilityUUIDs
```
I double checked that UUID 8CC8AD71-C38D-4C1A-A34B-DC78BCE76F57 exists in DVTPlugInCompatibilityUUIDs inside '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin'.

**Comment by yixiang** [comment]
OK, I don't know what I did made it work, but XVim2 is now working in my Xcode 9.3 beta 4.

**Comment by pebble8888** [comment]
An major cause is that Xcode9.3 beta4 has empty `IDEPegasusSourceEditor.ideplugin` which XVim use.
```
$ du -sh /Applications/Xcode.app/Contents/PlugIns/IDEPegasusSourceEditor.ideplugin/
 28K	IDEPegasusSourceEditor.ideplugin/
```
1) Apple is WIP, so we need to wait.
or 
2) There is what we need to modify something.

**Comment by pitoneux** [comment]
well I just filed another one... https://bugreport.apple.com/web/?problemID=39015122

**Comment by keith** [comment]
It looks like some internal classes got moved around here. Here's the new hierarchy of the source editor:

```
IDESourceEditor.IDESourceEditorView
   | DVTSourceEditor.DVTPegasusSourceEditorView
   |    | SourceEditor.SourceEditorView
   |    |    | NSView
   |    |    |    | NSResponder
   |    |    |    |    | NSObject```

**Comment by pebble8888** [comment]
It looks like we need more swift method calling wrapper (about 5~10 method and property).
For example, 
```
$ xcrun swift-demangle __T012SourceEditor0aB4ViewC9firstRectSC6CGRectVSC8_NSRangeV17forCharacterRange_SpyAHGSg06actualJ0tF
_T012SourceEditor0aB4ViewC9firstRectSC6CGRectVSC8_NSRangeV17forCharacterRange_SpyAHGSg06actualJ0tF ---> SourceEditor.SourceEditorView.firstRect(forCharacterRange: __C._NSRange, actualRange: Swift.UnsafeMutablePointer<__C._NSRange>?) -> __C.CGRect
```
```
$ xcrun swift-demangle  __T012SourceEditor0aB11ContentViewC37accessibilityInsertionPointLineNumberSiyF
_T012SourceEditor0aB11ContentViewC37accessibilityInsertionPointLineNumberSiyF ---> SourceEditor.SourceEditorContentView.accessibilityInsertionPointLineNumber() -> Swift.Int
```

**Comment by sarah** [comment]
Just here to add a +1 to seeing this issue.

**Comment by eclectocrat** [comment]
+1

**Comment by pebble8888** [comment]
Xcode9.3 is almost supported in branch `develop` or tag `xcode9.3`.
Use branch `master` or tag `xcode9.2` for Xcode9.2.

Some feature is not supported.
You can check to grep `XCODE93` for the entire source.

For drive force to develop, 
https://www.bountysource.com/teams/xvim

**Comment by pebble8888** [comment]
@hyouuu
Fixed. Please check it.

**Comment by solidcell** [comment]
I was able to successfully `make`, but there's no vim behavior in Xcode. Is it working for others?

**Comment by hyouuu** [comment]
Confirmed develop works - thanks so much @pebble8888 !

**Comment by hyouuu** [comment]
I would vote for search functionality to be fixed first :D

**Comment by darkamenosa** [comment]
> Confirmed develop works - thanks so much @pebble8888 !

How did you do that? I switched to develop branch and rebuilt it. It didn't work for me

**Comment by darkamenosa** [comment]
I created new certificate and signed again. After that, switched branch to develop. And followed installation step again. It worked! 

Thanks guys!

**Comment by hieonn** [comment]
Just like other guys' comments, changing the branch into development and make uninstall and make again. then you would be able to have working version on Xcode 9.3. I have big respect for the contributors and huge thanks. Thanks again. - expect escaping from Apple's Tyranny

**Comment by pebble8888** [comment]
Now, master branch is for Xcode9.3.
