### ISSUE TITLE
Status bar covers bottom line of code

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim2#11]
The status bar covers the last line of code. Not sure if theres an option to inject some padding to the source view bottom?

Otherwise its not a huge behaviour, but did confuse me the first or second time I switched to the assistant editor using `ctrl+w l`

**Comment by antmd** [comment]
Hi, the latest version should fix this.

**Comment by ober01** [comment]
yes, it fixed

**Comment by squarefrog** [comment]
Confirmed fixed.

**Comment by ooopscc** [comment]
It seems bug again in recently.

when find next use `*`, the matched line shows below the status bar
