### ISSUE TITLE
Breaks Fastlane's scan (unit testing)

### ISSUE THREAD

**Issue by plm75** [XVimProject/XVim2#111]
when trying to launch unit tests with Fastlane's scan, I get the following error message:

/Users/user/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1, NSBundlePath=/Users/user/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin, NSLocalizedDescription=The bundle “XVim2” couldn’t be loaded because it is damaged or missing necessary resources.}

**Comment by mmcc007** [comment]
In my case, I get this warning, and the tests run and complete
