### ISSUE TITLE
Gray bar showing up at bottom of editor

### ISSUE THREAD

**Issue by keithZumper** [XVimProject/XVim2#112]
<img width="986" alt="screen shot 2018-02-09 at 2 32 33 pm" src="https://user-images.githubusercontent.com/25964151/36053321-1e3c0d64-0da6-11e8-8d60-40b9c76953bc.png">

**Comment by keithZumper** [comment]
Anyway to hide this?

**Comment by pebble8888** [comment]
Add `set laststatus=0` to your .xvimrc
Check on `develop` branch.
