### ISSUE TITLE
$ to jump to en of line

### ISSUE THREAD

**Issue by sebbo176** [XVimProject/XVim2#113]
Hi. I love this plugin! But I'm missing the "$" char to move the cursor to the end of the line?

I can use "0" to get to the start of any line but how do you jump to the end of a line without "$"?

**Comment by wangchou** [comment]
"$" works for me. 
Xcode Version 9.2 (9C40b) and latest XVim2 from master branch.

**Comment by sebbo176** [comment]
I also have 9.2 9c40b from master. But I got it working, It only works on English keyboards. If I have Swedish settings and type $, it doesn't work.
