### ISSUE TITLE
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'

### ISSUE THREAD

**Issue by CallumHoward** [XVimProject/XVim2#114]
I am getting this error when attempting to build XVim2:
```
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.12.sdk'
```

I have codesigned, and I have had XVim2 working in the past on older Xcode versions.  
I am on the latest HEAD, `6486e63`
Xcode 9.2
macOS 10.13.3

full make output here:
https://gist.github.com/CallumHoward/620a0a049d486b0d7c42e381487ec308

**Comment by pebble8888** [comment]
We don't support older version Xcode.
