### ISSUE TITLE
Not showing with xcode release 9.3

### ISSUE THREAD

**Issue by pitoneux** [XVimProject/XVim2#122]
Installed new xcode 9.3 with the app store, after installing the "tools", sudo make vim2, launch xcode, didn't get the load bundle dialog, exit, defaults deleted ----xcode-9.3, launch xcode, get the dialog to loadbundle, hit "load bundle", nothing show up.

help!

I'm sure I'm note the only one...

**Comment by pitoneux** [comment]
Found a work around to load the plugin but it is not working still... 

look carefully at the make... the last line for me was:

> Signing Identity:     "-"

I did a manual signing (take a long time) of the xcode build (sudo codesign -f -s ... ) and now xvim load fine but doesn't seem to work...

**Comment by zyqhi** [comment]
XVim2 was loaded when start Xcode, but still not work. I am using Xcode 9.3.

**Comment by bduhbya** [comment]
I see the same issue with XVim2 not working with Xcode 9.3 release downloaded via App Store.

- Ran manual code sign.
- Ran "make" from master and develop branches.

I see Xcode ask to load bundle after successful build, but once Xcode starts it is in the normal editing style without XVim.  At "make" time I see a handful of possible errors, but I do not know if they are related to the current failures:

```
2018-03-30 14:22:10.651 xcodebuild[84439:2728321] WARNING: Failed to load plugin at path: "/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signing blocked mmap() of '/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2'
	/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2, NSDebugDescription=dlopen_preflight(/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signing blocked mmap() of '/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2'
	/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1, NSBundlePath=/Users/<MY_USER_OBFUSCATED>/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin, NSLocalizedDescription=The bundle “XVim2” couldn’t be loaded because it is damaged or missing necessary resources.
```

Thanks in advance for taking a look.  This tool is great to have.

**Comment by liuning0930** [comment]
you  can download the develop branch , it works for me.

**Comment by ooopscc** [comment]
move motion actions work well, but still no ex mode, no bottom bar is showed.
![image](https://user-images.githubusercontent.com/1056803/38202617-eeb1a21e-36ce-11e8-97e1-b99c3a57ec5a.png)

**Comment by veegee** [comment]
Can confirm that the current develop branch works to some extent. The plugin compiles and loads, most things seem to work, but still no ex mode as shown above by @ooopscc.

**Comment by YANOUSHek** [comment]
@ooopscc @veegee while ex mode bar is not visible ex mode itself works like a charm – you can trigger commands, but you're not able to see them on screen which is a bit weird.

**Comment by veegee** [comment]
@YANOUSHek confirmed. XCode is such a pile of trash. I think I'll just fully move to AppCode and avoid all this silliness.

**Comment by YANOUSHek** [comment]
@veegee I wouldn't say it's a pile of trash, but please remember that there's no official support for Xcode plugins so they might break with each Xcode update. And remember how much this says about the guys who develop XVim / XVim2 :)

**Comment by veegee** [comment]
@YANOUSHek I'm absolutely praising all the XVim engineers. It's XCode itself that's miserable.

**Comment by troyibm** [comment]
confirm that develop branch worked for me.  master didn't.  xcode9.3 tag didn't work either.

AppCode?  I'd love to dump Xcode for this very reason - no native vi support. :P

**Comment by philosopherdog** [comment]
So is the develop branch working with 9.3? Is it wise to go ahead and update Xcode or??

**Comment by ooopscc** [comment]
@philosopherdog For me, no. So I have to back to 9.2.

**Comment by timothycosta** [comment]
Develop is working for me in 9.3.  Master was not.

**Comment by pebble8888** [comment]
close for duplication.
Check #108
