### ISSUE TITLE
Using `gd` to go to a local declaration

### ISSUE THREAD

**Issue by 99arobe** [XVimProject/XVim2#14]
Both Vim and Xvim have option to use `gd` to jump to the declaration of a method, property, etc. XVim2 does not yet have this behaviour. 

The Xcode equivalent shortcut is `^`+`CMD`+`j`.

**Comment by Desgard** [comment]
Yes! Mixed use `vim` and `xcode` shortcut key is very strange. And after I press `^` + `<CMR>` + `j`, I always want to use `<CR>` + `t` to jump back, but it is invalid.  😭

**Comment by fuzhuo** [comment]
Add more..
⌃o or ⌃t to go backward, Xcode default shortcut is ⌃⌘←
⌃p like ctrlP plugin to quick goto file, Xcode default shortcut with ⇧⌘O

**Comment by 99arobe** [comment]
@fuzhuo XVim2 seems to be able to jump backwards for me using `CTRL-o` perfectly fine (the equivalent of ⌃⌘←). It doesn't however seem to jump forwards using `CTRL-i`. 

@Desgard I've never used `<CR>` + `t`to jump back. How does that work?

I think that the `gd` command is a separate thing here. I haven't had a look at how this all works under the hood but I'm guessing that it _might_ be a simple fix to just map `gd` to Xcode's own `^`+`CMD`+`j`shortcut somehow?

@fuzhuo In terms of implementing a CtrlP, fuzzy finder - doesn't using Xcode's own `CMD`+`SHIFT`+`o` work well enough?

**Comment by PopeyeLau** [comment]
create `.xvimrc` file.
`nmap gd :xccmd jumpToDefinition<CR>`
works for me.

**Comment by antmd** [comment]
Just pushed a change which should fix gd, ^o, ^t, etc.

**Comment by 99arobe** [comment]
Great stuff @antmd. 

I've pulled and can confirm that `gd` now works for me as intended without any custom mappings. 

@PopeyeLau Yeah those mappings were my first thought. Out of interest, is there a list of commands anywhere that I can easily access (for `jumpToDefinition ` and `goForwardInHistoryByCommand`, etc)?

**Comment by PopeyeLau** [comment]
@99arobe

Here's a link to actions which can be invoked from the XCode menu.（old version）
https://github.com/JugglerShu/XVim/blob/master/Documents/Developers/MenuActionList.txt

**Comment by 99arobe** [comment]
@PopeyeLau That's very useful. Thanks.
