### ISSUE TITLE
I can't work on Xcode9.2 with Vim2, why?

### ISSUE THREAD

**Issue by crazyherozk** [XVimProject/XVim2#141]
I has done all work according to the README.md,but it hasn't work......help me.my xcode's version is 9.2.

**Comment by pebble8888** [comment]
Use tag `xcode9.2`.
The master and develop branch is for Xcode9.3.

**Comment by MicroConan** [comment]
I can't work on Xcode9.2 too.

**Comment by crazyherozk** [comment]
maybe you need to make coding sign certificate that named 'XcodeSigner` and  run `sudo codesign -f -s XcodeSigner /Applications/Xcode.app` in shell

**Comment by 99arobe** [comment]
@crazyherozk @MicroConan  Can you provide much more detail about the steps you've taken, any errors you've experienced, commit shas that you are building from, etc, etc? It's difficult for anyone to replicate your issue otherwise.

**Comment by TahaMagdy** [comment]
@pebble8888 "Use tag `xcode9.2`." might not be as clear as I should be.
#### This solved my problem.
`$ git checkout xcode9.2`

then `make uninstall` if you've installed an incompatible version (which was not working)
After that `make`

Happy Vimming!

**Comment by bovink** [comment]
@TahaMagdy 

you saved my time, thank you!
