### ISSUE TITLE
do not support Xcode9.3?

### ISSUE THREAD

**Issue by dutchmanxj** [XVimProject/XVim2#142]
[Write issue description here]

```
-------- Debug Info -------
XVim2 revision : 6486e637192360ad99ee9ab7768fb3c486fba459
OS Version : Version 10.13.3 (Build 17D102)
Xcode Version : 9.3

--- .xvimrc ---
N/A
--------------
```

**Comment by julianschacherpp** [comment]
I just compiled the latest version of XVim2 and it appears to work for 9.3. I didn't test it much, but the basic functionality is there.

**Comment by philosopherdog** [comment]
@julianschacherpp which branch are you using?

**Comment by julianschacherpp** [comment]
I was using the master branch.

**Comment by jooyyy** [comment]
@julianschacherpp  will you share your source code?

**Comment by pebble8888** [comment]
duplicate #108

**Comment by julianschacherpp** [comment]
@jooyyy I don't need to share the source code, it's the code of this repo (master branch). Or am I understanding your question wrong?
