### ISSUE TITLE
Codesign doesn't finish

### ISSUE THREAD

**Issue by hiel** [XVimProject/XVim2#143]
I create XcodeSigner certificate
and
sudo codesign -f -s XcodeSigner /Applications/Xcode.app

'replacing existing signature' message display and
doesn't finish.

why?

**Comment by JugglerShu** [comment]
How long did you wait for the command?
It is supposed to take a while.

**Comment by crazyherozk** [comment]
about 5min
发自我的 iPhone

**Comment by JugglerShu** [comment]
Then just wait. It could take more than 5min.

**Comment by hiel** [comment]
Thanks, I solved this.

**Comment by hugobast** [comment]
@hiel I have this issue, did waiting work?

**Comment by hugobast** [comment]
Ok waiting more worked but one wrinkle, I had an old expired XcodeSigner (same name as the readme) if you have duplication in name it won't work, delete the old/pick a new name
