### ISSUE TITLE
not redraw cursor to type Shift + o on }

### ISSUE THREAD

**Issue by pebble8888** [XVimProject/XVim2#144]
![capture](https://user-images.githubusercontent.com/1704383/39403049-98ec5a94-4bab-11e8-9533-1ac9929942dc.gif)

**Comment by Colafroth** [comment]
How do you have the `redraw` type of cursor in Xcode?

**Comment by pebble8888** [comment]
It's too difficult to fix the issue for `set blinkcursor`.

**Comment by kylefleming** [comment]
> It's too difficult to fix the issue for `set blinkcursor`.

Could you explain this a bit more? What part of it is the difficult part? Maybe someone in the community would be willing to take a pass at fixing it, especially if the problem was described in more detail.

**Comment by pebble8888** [comment]
Anyone who want to fix it needs reverse engineering xcode written in swift.

**Comment by nuynait** [comment]
I didn't set `blinkcursor`, but I always experience this issue when click `o` under a function and it deletes the `}`

**Comment by nuynait** [comment]
Attached a gif screencast here. 
![CleanShot 2021-04-27 at 10 05 05](https://user-images.githubusercontent.com/2152195/116255408-34c4f280-a740-11eb-9727-f6594a412a20.gif)
