### ISSUE TITLE
PlugIns folder changed to => /Applications/Xcode.app/Contents/PlugIns???

### ISSUE THREAD

**Issue by fedry** [XVimProject/XVim2#146]
After running 'make', XVim plugin is still not detected by Xcode.
Then I move the plugin file to folder /Applications/Xcode.app/Contents/PlugIns and it is working.

Should the dstPath in ./XVim2.xcodeproj/project.pbxproj file be updated?

**Comment by Chrinkus** [comment]
@fedry I *just* decided to give Xcode another shot after finding this Vim plugin. Installed it a week ago, used it a few times and it was good. Now it doesn't work. If this is the reason, can you tell me which file you moved and from where?

**Comment by fedry** [comment]
I think it is easier to update ./XVim2.xcodeproj/project.pbxproj file.
Search for "dstPath" in the file, update the value to be pointing to "/Applications/Xcode.app/Contents/PlugIns" folder.

**Comment by Chrinkus** [comment]
Thanks, I found the file and moved it but that didn't fix my problem, I still can't use Vim anymore in Xcode. Tried a fresh install too.

**Comment by fedry** [comment]
Have you re-codesign your Xcode with your own key?

Other than that, I have no more idea what might be the problem.

**Comment by Jamongkad** [comment]
@fedry where is the plugin file you manually moved? My Xcode (9.3.1) asks if I want to load the Xvim2 plugin. After clicking on "load plugin" it still can't use Vim. Perhaps this can solve my problem.

**Comment by fedry** [comment]
@Jamongkad honestly I don't really know what the problem is, maybe the author will help us here. Other than trying re-codesign your Xcode, I have no other idea to troubleshoot the issue. :)

https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by sendyhalim** [comment]
Hmm weird, I tried to install it and it works fine. 
Steps that I did
1. Clone https://github.com/XVimProject/XVim2 
2. `cd xvim2`
3. `make uninstall`
4. Code sign xcode~
5. Back to xvim2 dir -> `make`

**Comment by shingargle** [comment]
I made a simple mistake.
I used an expired certificate :P

@fedry and @sendyhalim 
I noticed at your comments.
Thanks!

re-make certificate and re-sign and then it works fine now.

**Comment by Chuabacca** [comment]
I had a similar problem where XVim stopped working suddenly. I resigned Xcode and now it's working again! Thanks for the helpful tips here!
