### ISSUE TITLE
wrong cursor position after ca"

### ISSUE THREAD

**Issue by sherzinger** [XVimProject/XVim2#147]
Given a line like `let a = "abc"` go anywhere within the " and type `ca"` and the cursor will jump one position too far to the left.

I think it actually jumps over all left sided whitespace. In a line consisting of several spaces it will just jump to the beginning of the line e.g. `<SPACE><SPACE><SPACE><SPACE>"abc"`. + `ca"` will erase the entire line.

**Comment by patrickchin** [comment]
I believe vim behaves this way also, so this is actually correct.

**Comment by sherzinger** [comment]
Wow, you're actually right. I never noticed before.
I'm curious for the reasoning behind this behaviour, especially because vim doesn't do this with brackets. (e.g. `ca(`)

Guess I'll close this issue again.
