### ISSUE TITLE
XVim2; installed but not working!

### ISSUE THREAD

**Issue by TahaMagdy** [XVimProject/XVim2#149]
Xcode: 9.2

I have installed XVim2 as in the README.md.

![screen shot 2018-05-29 at 2 22 45 am](https://user-images.githubusercontent.com/18517169/40632424-4fb63324-62e7-11e8-9c6b-2386c20e8742.jpg)

What's wrong?!

**Comment by pebble8888** [comment]
#141

**Comment by TahaMagdy** [comment]
@pebble8888  But I did work.
