### ISSUE TITLE
Can we install XVim without resign Xcode if we have an apple developer account?

### ISSUE THREAD

**Issue by fuzhuo** [XVimProject/XVim2#15]
Resigned Xcode works fine at most time, but I meet an issue when I try pair over network in Xcode9 with connect to an AppleTV4K (There is no USB port in TV4K wireless is by design).
Resigned Xcode can not pair successfully, it always failed with a error message "General failure while pairing over the network", The original Xcode can pair without errors, Apple seems check Xcode signature when do pair.

I see there is a plugin available in the AppStore named BlockComment for Xcode https://itunes.apple.com/cn/app/blockcomment-for-xcode/id1246672247?mt=12 seems it is official supported.

I tried change XVim sign to my developer account but plugin not loaded on the original Xcode.

**Comment by mplorentz** [comment]
I haven't tried this, but [this guy](https://johntmcintosh.com/blog/2016/09/30/xcode8-extensions) seems to have found a way to restore Xcode's original signature before his deployments. Maybe you can use the same process.

**Comment by fuzhuo** [comment]
Thanks, I workaround by copy two Xcode9, one un-sign with XVim plugin, another one keep origin signed to do other security jobs..
