### ISSUE TITLE
Xcode 9.4

### ISSUE THREAD

**Issue by kylelol** [XVimProject/XVim2#151]
I upgraded to Xcode 9.4 and now XVIM will not load anymore. I tried to uninstall and reinstall it but no luck. Xcode asks me if I want to reload the bundle after I do that, but once I'm inside, the plugin does not work. Any ideas?

**Comment by mannd** [comment]
Did you resign the new Xcode version?  Every time Xcode is updated it needs to be resigned.

**Comment by crazyherozk** [comment]
Signed code to xcode again please.

发自我的 iPhone

**Comment by kylelol** [comment]
Will try that. I don't need to generate a new certificate correct?

**Comment by kylelol** [comment]
That worked, than you!
