### ISSUE TITLE
Support for Xcode 9.4?

### ISSUE THREAD

**Issue by dhalman** [XVimProject/XVim2#152]
Hello, 

Getting this error running "make" after the last Xcode 9.4 update:

CompileC build/XVim.build/Release/XVim.build/Objects-normal/x86_64/IDESourceCodeEditor+XVim.o XVim/IDESourceCodeEditor+XVim.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/lytic/software/utils/XVim
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=120 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -gmodules -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wmissing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DXVIM_XCODE_VERSION=5 -DOBJC_OLD_DISPATCH_PROTOTYPES=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.7 -g -Wsign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -IXcodeClasses/Xcode4 -IXVim -I/Users/lytic/software/utils/XVim/build/Release/include -I/Users/lytic/software/utils/XVim/build/XVim.build/Release/XVim.build/DerivedSources/x86_64 -I/Users/lytic/software/utils/XVim/build/XVim.build/Release/XVim.build/DerivedSources -F/Users/lytic/software/utils/XVim/build/Release -F/Applications/Xcode.app/Contents/Developer/../Frameworks -F/Applications/Xcode.app/Contents/Developer/../PlugIns -F/Applications/Xcode.app/Contents/Developer/../SharedFrameworks -include /Users/lytic/software/utils/XVim/build/SharedPrecompiledHeaders/XVim-Prefix-apzdrfxkmrvlyucoeexofpqjktwu/XVim-Prefix.pch -MMD -MT dependencies -MF /Users/lytic/software/utils/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/IDESourceCodeEditor+XVim.d --serialize-diagnostics /Users/lytic/software/utils/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/IDESourceCodeEditor+XVim.dia -c /Users/lytic/software/utils/XVim/XVim/IDESourceCodeEditor+XVim.m -o /Users/lytic/software/utils/XVim/build/XVim.build/Release/XVim.build/Objects-normal/x86_64/IDESourceCodeEditor+XVim.o

** BUILD FAILED **

The following build commands failed:
	CompileC build/XVim.build/Release/XVim.build/Objects-normal/x86_64/DVTTextSidebarView+XVim.o XVim/DVTTextSidebarView+XVim.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [release] Error 65

**Comment by EmDee** [comment]
I can build it for Xcode 9.4. Have you already pulled the changes from 5 days ago (https://github.com/XVimProject/XVim2/commit/784568e46a703aef828abacfe82fb09c1f9e4cda)?

**Comment by dhalman** [comment]
Ah, the pull aborted due to local changes. Apologies, closing :)

(And thanks for maintaining support!!) 👍
