### ISSUE TITLE
(XCode 9.4) Failed to load plugin at path

### ISSUE THREAD

**Issue by JaviOverflow** [XVimProject/XVim2#156]
Using XCode 9.4, MacOS High Sierra 10.13.5

I followed the steps and I'm getting the following message when executing make. Any idea what could be wrong?

> xcodebuild -configuration Release 
> 2018-06-08 21:15:23.373 xcodebuild[1208:39176] WARNING: Failed to load plugin at path: "/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
> 	/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signing blocked mmap() of '/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2'
> 	/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2, NSDebugDescription=dlopen_preflight(/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
> 	/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signing blocked mmap() of '/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2'
> 	/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1, NSBundlePath=/Users/overflow/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin, NSLocalizedDescription=The bundle “XVim2” couldn’t be loaded because it is damaged or missing necessary resources.}

**Comment by Chuabacca** [comment]
Just checking that you did all the obvious stuff.
* Pulled the latest `master` branch?
* Signed Xcode with your custom cert (need to resign if you upgraded Xcode)?
* ran `make` in the correct XVim2 directory?

I just resigned and built the latest `master` of XVim2 after updating to Xcode 9.4. Everything is working for me.

**Comment by JaviOverflow** [comment]
I tried what you said and still not working...

When I run make, I get the following message

> ...
> 
> CodeSign build/Release/XVim2.xcplugin
>     cd /Users/overflow/MyDocuments/Downloads/XVim2
>     export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
>     
> Signing Identity:     "-"
> 
>     /usr/bin/codesign --force --sign - --timestamp=none /Users/overflow/MyDocuments/Downloads/XVim2/build/Release/XVim2.xcplugin
> 
> ** BUILD SUCCEEDED **

Is it normal that i'm getting a dash at Signing Identity?

**Comment by Chuabacca** [comment]
Hmm, I don't know enough about what's going on to really be helpful... You followed all the signing steps from this repo? https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by Chuabacca** [comment]
Yes, I had to re-sign and rebuild recently and paid attention to my
terminal output. The signing identity is a dash. Sorry I wasn’t able to
help more.

**Comment by mplorentz** [comment]
Maybe try opening XVim2.xcodeproj and building and running that way?
