### ISSUE TITLE
Xcode 10: Status bar is empty in normal mode

### ISSUE THREAD

**Issue by JadianZheng** [XVimProject/XVim2#157]
Same to title, see the follow:
![screen shot 2018-06-10 at 09 45 13](https://user-images.githubusercontent.com/3894891/41197492-28b735b0-6c93-11e8-8bd2-bc8c1bf7ec8e.png)

**Comment by gaoyuqiang** [comment]
xcode 9.2 have a same problem

**Comment by fuzhuo** [comment]
And, for xcode10-beta there is a unexpected status bar in the debug console, it will stay on top of the last debug line.

**Comment by kr15hna** [comment]
make sure the value for laststatus is 2 in your .xvimrc
