### ISSUE TITLE
Xcode 9.4.1 not working.

### ISSUE THREAD

**Issue by MasterBeta** [XVimProject/XVim2#159]
Just upgraded to 9.4.1，xvim2 just not working after I followlling the install instructions as usual:

1: git fetch & pull on develop branch of this repo. (uuid of 9.4.1 is included.)

2: resign xcode use:
`sudo codesign -f -s XcodeSigner /Applications/Xcode.app`

3: cd XVim2 and make.

Any same problem here?

**Comment by gidjituser** [comment]
I am using the master branch and it seems okay. If you accidentally opened Xcode before running your commands you may need to run 

defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-9.4.1

**Comment by JaviOverflow** [comment]
What could I do if I get the following error while trying to sign xcode?

> XcodeSigner: no identity found

**Comment by MasterBeta** [comment]
@gidjituser Thanks. I've switched to master branch and re-make. Everything works fine now.

BTW: Branch develop is still broken on Xcode 9.4.1.

**Comment by JaviOverflow** [comment]
thanks @MasterBeta !

By the way, I installed the version at tag xcode9.4 and it worked everything so far (I can perfectly see the big caret and I can undo using 'u').

**Comment by troyibm** [comment]
Not working for me.  Build worked.  codesign worked (from what I can tell).  Got prompt to load XVim2 bundle on Xcode start.  Recent projects selector didn't show on that start so Quit and restarted.  No XVim menu anywhere and vi keys don't work.  I also had to force quit Xcode on that second start.  I hate Xcode and Apple on why that make this so difficult.

**Comment by mplorentz** [comment]
I was having trouble installing for Xcode 9.4.1 as well. `make` was succeeding but when I launched Xcode there was no prompt to load the plugin and no vim key binds. I'm using the `master` branch.

What fixed it for me was opening `XVim2.xcodeproj` in Xcode and clicking Build and Run. Then I restarted Xcode and now it works.

**Comment by LoLiik** [comment]
@mplorentz your solution hepls me to see the prompt, but no vim in xcode...
should i so something else? create .xvimrc for example?

**Comment by mplorentz** [comment]
@LoLiik I'm not sure. You might try `make` from the command-line again. If that doesn't work I would start over with the signing instructions, making sure your `xcode-select` is pointed at the right Xcode, and making sure that you are on the `master` branch.

**Comment by LoLiik** [comment]
@mplorentz 
succeded with running Xcode with sudo and then running project XVim2.xcodeproj
but doesn't help for ordinary xcode...

`The following build commands failed:
	PrecompileSwiftBridgingHeader normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
make: *** [release] Error 65`

**Comment by timothycosta** [comment]
@JaviOverflow's 9.4 tag tip worked for me.  Current master compiled and installed fine.  But normal mode did not work at all and insert mode was badly broken.

**Comment by hieonn** [comment]
XVIM2 has not been working by following the instruction, but It works now by signing AGAIN the XCode along the link  https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md in very first step. (The signing takes quite long time for your information)
The master branch works for now. Thanks for your works and I would never like Apple.

**Comment by nightwolf-chen** [comment]
cool, @gidjituser you save the day!

**Comment by hieonn** [comment]
@lazywhite Yes, that's what I wrote. I had been a user of the XVIM in previous versions and I needed to make a signing Xcode again even I had been using previous version.

**Comment by sashaweiss** [comment]
`master` wasn't working for me (wasn't seeing highlights in Visual mode, couldn't undo, similar to what others have said). However, checking out the `xcode9.4` tag and rebuilding fixed it for me! Thanks @JaviOverflow!

**Comment by kagemiku** [comment]
I found the broken commit by using `git bisect`.

The broken commit is [change swift function pointer address for Xcode10](https://github.com/XVimProject/XVim2/commit/dae173f3ee25f6473e8eb10983999d5afa596bae)
The parent commit of it is [change from Xcode9.3 header to Xcode10](https://github.com/XVimProject/XVim2/commit/d95e598fb023d2229e9d50d0db323d1a3b89dba4), this is working well.

**Comment by squarefrog** [comment]
@kagemiku this worked for me too in 9.4.1. Thank you!!
