### ISSUE TITLE
Xcode 10: Crash while edit in 'build phases'

### ISSUE THREAD

**Issue by JadianZheng** [XVimProject/XVim2#161]
Step:
1. Install xvim2 and enable it.
2. Select any project's `Build Phases`, edit in any script, just press any key

**(It crash even I disable xvim, but I can did this before install xvim.)**

**Comment by pebble8888** [comment]
I fixed it in develop branch. Please check it.

**Comment by JadianZheng** [comment]
@pebble8888 Thank you. This work for me. 
But **another problem** is, `it can't enter vim mode.`

**Comment by pebble8888** [comment]
I just prevent crashing in that window.
I have no time to support vim in that window.
Please raise issue that feature for someone has enough time for developing.

**Comment by JadianZheng** [comment]
@pebble8888 Ok, thank you for your developing.
