### ISSUE TITLE
Unexpected vim status bar in debug console panel

### ISSUE THREAD

**Issue by qiudaomao** [XVimProject/XVim2#170]
The status bar should only shows in the edit panel but not the console panel.
As below picture shows the unexpected status bar in console panel also has layout issue, it shows on the top of the last line, I'm not able to debug with lldb command.
 
![](https://i.loli.net/2018/07/29/5b5d4ebcf3cae.png)

**Comment by hawflakes** [comment]
@fuzhuo My work-around is to click the trash to get the prompt up on top. I did wish it were disabled, too.

**Comment by kabouzeid** [comment]
This is a major annoyance for me too

**Comment by pebble8888** [comment]
I have not expericenced the case in my environment.

**Comment by kabouzeid** [comment]
It disappeared for me at XCode 10 GM too 🎉
