### ISSUE TITLE
Xcode 10 beta 5: 'dd' action crash after 'yy' action

### ISSUE THREAD

**Issue by JadianZheng** [XVimProject/XVim2#174]
Same to title. 

**Import**:
1. It happen when the `yy` action block(), you can reappear this by fast opeartion.
2. **It happen in playground only**, I did't found this issue in my other iOS project.

Version:
0bc3df2 (Last commit)

**Comment by kabouzeid** [comment]
Also happens without yy for me

**Comment by pebble8888** [comment]
Can't reproduce in Xcode10 GM.
Please write unit test code crash XVim.
