### ISSUE TITLE
Change inside "" command makes Xcode 9 crash

### ISSUE THREAD

**Issue by haarc** [XVimProject/XVim2#18]
When using the vim shortcut ci" to change the symbols inside "", Xcode 9 crashes instantly.

**Comment by rudedogg** [comment]
This is working for me

**Comment by haarc** [comment]
I found out more about this behaviour:
It occurs when typing " and is reproducible (on my machine that is). The interesting thing is, that it only happens when I use an English (U.S. / International) keyboard layout. When another keyboard layout is in use and " is typed it actually works and so do the related vim commands.

**Comment by antmd** [comment]
Please paste a crash report here with the bit showing the crashed thread backtrace (or the whole thing).

**Comment by haarc** [comment]
The following should be the interesting part:

> Process:               Xcode [20756]
> Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
> Identifier:            com.apple.dt.Xcode
> Version:               9.0 (13247)
> Build Info:            IDEFrameworks-13247000000000000~26
> App Item ID:           497799835
> App External ID:       823595305
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Xcode [20756]
> User ID:               501
> 
> PlugIn Path:             /Users/USER/Library/Application Support/Developer/*/XVim2
> PlugIn Identifier:       net.JugglerShu.XVim2
> PlugIn Version:          1.0 (1)
> 
> Date/Time:             2017-10-12 13:49:56.611 +0200
> OS Version:            Mac OS X 10.12.6 (16G29)
> Report Version:        12
> Anonymous UUID:        22B61CA3-A1EC-DDFA-809F-07D8BC4808A1
> 
> Sleep/Wake UUID:       BC0B66C3-C433-433C-B868-A78EFA29FE6B
> 
> Time Awake Since Boot: 62000 seconds
> Time Since Wake:       5200 seconds
> 
> System Integrity Protection: disabled
> 
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> ProductBuildVersion: 9A235
> UNCAUGHT EXCEPTION (NSInvalidArgumentException): *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil
> UserInfo: (null)
> Hints: 
>  
> Backtrace:
>   0   __exceptionPreprocess (in CoreFoundation)
>   1   DVTFailureHintExceptionPreprocessor (in DVTFoundation)
>   2   objc_exception_throw (in libobjc.A.dylib)
>   3   -[__NSArrayM insertObject:atIndex:] (in CoreFoundation)
>   4   -[_TtC22IDEPegasusSourceEditor20SourceCodeEditorView(XVim) xvim_keyDown:] at /Users/chaar/dev/XVim2/XVim2/Xcode/IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.m:118 (in XVim2)
>   5   -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] (in AppKit)
>   6   -[NSWindow(NSEventRouting) sendEvent:] (in AppKit)
>   7   -[IDEWorkspaceWindow sendEvent:] (in IDEKit)
>   8   -[NSApplication(NSEvent) sendEvent:] (in AppKit)
>   9   -[IDEApplication sendEvent:] (in IDEKit)
>  10   -[NSApplication run] (in AppKit)
>  11   NSApplicationMain (in AppKit)
>  12   start (in libdyld.dylib)
>  
> abort() called
> 
> Application Specific Signatures:
> NSInvalidArgumentException
> 
> Application Specific Backtrace 1:
> 0   CoreFoundation                      0x00007fff964cc2cb __exceptionPreprocess + 171
> 1   DVTFoundation                       0x00000001055ff077 DVTFailureHintExceptionPreprocessor + 274
> 2   libobjc.A.dylib                     0x00007fffab2e448d objc_exception_throw + 48
> 3   CoreFoundation                      0x00007fff963e4f22 -[__NSArrayM insertObject:atIndex:] + 1442
> 4   XVim2                               0x000000011982f729 -[_TtC22IDEPegasusSourceEditor20SourceCodeEditorView(XVim) xvim_keyDown:] + 124
> 5   AppKit                              0x00007fff948322cc -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 4086
> 6   AppKit                              0x00007fff94830f0a -[NSWindow(NSEventRouting) sendEvent:] + 541
> 7   IDEKit                              0x0000000106fb15d5 -[IDEWorkspaceWindow sendEvent:] + 154
> 8   AppKit                              0x00007fff946b64a8 -[NSApplication(NSEvent) sendEvent:] + 4768
> 9   IDEKit                              0x0000000106ffbb03 -[IDEApplication sendEvent:] + 921
> 10  AppKit                              0x00007fff93f30427 -[NSApplication run] + 1002
> 11  AppKit                              0x00007fff93efae0e NSApplicationMain + 1237
> 12  libdyld.dylib                       0x00007fffabbca235 start + 1
> 13  ???                                 0x0000000000000002 0x0 + 2
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libsystem_kernel.dylib        	0x00007fffabcf8d42 __pthread_kill + 10
> 1   libsystem_pthread.dylib       	0x00007fffabde6457 pthread_kill + 90
> 2   libsystem_c.dylib             	0x00007fffabc5e420 abort + 129
> 3   com.apple.dt.IDEKit           	0x0000000106f69d43 +[IDEAssertionHandler _handleAssertionWithLogString:assertionSignature:assertionReason:extraBacktrace:] + 1370
> 4   com.apple.dt.IDEKit           	0x0000000106f6b54f -[IDEAssertionHandler handleUncaughtException:] + 1099
> 5   com.apple.dt.IDEKit           	0x0000000106f6b621 IDEHandleUncaughtException + 94
> 6   com.apple.CoreFoundation      	0x00007fff9654affa __handleUncaughtException + 746
> 7   libobjc.A.dylib               	0x00007fffab2e66f5 _objc_terminate() + 94
> 8   libc++abi.dylib               	0x00007fffaa7d3d49 std::__terminate(void (*)()) + 8
> 9   libc++abi.dylib               	0x00007fffaa7d37be __cxa_throw + 121
> 10  libobjc.A.dylib               	0x00007fffab2e45b6 objc_exception_throw + 345
> 11  com.apple.CoreFoundation      	0x00007fff963e4f22 -[__NSArrayM insertObject:atIndex:] + 1442
> 12  net.JugglerShu.XVim2          	0x000000011982f729 -[_TtC22IDEPegasusSourceEditor20SourceCodeEditorView(XVim) xvim_keyDown:] + 124 (_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.m:121)
> 13  com.apple.AppKit              	0x00007fff948322cc -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 4086
> 14  com.apple.AppKit              	0x00007fff94830f0a -[NSWindow(NSEventRouting) sendEvent:] + 541
> 15  com.apple.dt.IDEKit           	0x0000000106fb15d5 -[IDEWorkspaceWindow sendEvent:] + 154
> 16  com.apple.AppKit              	0x00007fff946b64a8 -[NSApplication(NSEvent) sendEvent:] + 4768
> 17  com.apple.dt.IDEKit           	0x0000000106ffbb03 -[IDEApplication sendEvent:] + 921
> 18  com.apple.AppKit              	0x00007fff93f30427 -[NSApplication run] + 1002
> 19  com.apple.AppKit              	0x00007fff93efae0e NSApplicationMain + 1237
> 20  libdyld.dylib                 	0x00007fffabbca235 start + 1

**Comment by antmd** [comment]
Thanks for the crash dump. Please pull the latest version, clean build, and try again.

**Comment by haarc** [comment]
Thanks for the fast reply! It does not crash anymore.
