### ISSUE TITLE
Help: How to debug xvim2

### ISSUE THREAD

**Issue by JadianZheng** [XVimProject/XVim2#180]
Same to title. 
Some crash happen in XCode 10, I want to fix it, but I don't know how to debug.
Can anyone spend some time to explain？

**Comment by 99arobe** [comment]
Hi @JadianZheng 

Have you watched [this video](http://www.youtube.com/watch?v=50Bhu8setlc&feature=youtu.be). 

Basically you need to add `set debug` to your `.xvimrc` file and reopen Xcode with XVim2. This will create a log file at the path `$HOME/.ximlog`, which you can view using `tail -f $HOME/.xvimlog` while you are using XVim2 commands in Xcode.

**Comment by JadianZheng** [comment]
@99arobe Thank you. I will watch it out later. 
Maybe document is better for me, do you have some idea?

**Comment by pebble8888** [comment]
I modified readme.md in `develop` branch.
See here.

https://github.com/XVimProject/XVim2/blob/develop/Documents/Contributing.md

**Comment by JadianZheng** [comment]
@pebble8888 Thank you.

**Comment by JadianZheng** [comment]
@pebble8888 
I tryed as the [Debugging](https://github.com/XVimProject/XVim2/blob/develop/Documents/Contributing.md#debugging) section say, but can't not run the Xcode instance. Because I use Xcode 10 - beta6?
I will try the another way, but I think the best is debug the Xcode instance directly.

**Comment by pebble8888** [comment]
@JadianZheng

Edit scheme - Run 
-> Info tab - Executable - Ask on Launch

And Xcode run -> Choose an app to run -> Select Xcode

**Comment by JadianZheng** [comment]
@pebble8888 Thank you. It works. I think I can make some contributing soon.

**Comment by JadianZheng** [comment]
@pebble8888 I have a another problem. 
How to chose the project when debug xvim2? It always open xvim2 now.

**Comment by JadianZheng** [comment]
@pebble8888 Thank you, I see it. Thanks for your patient help.
