### ISSUE TITLE
Xcode10 GM 'dd' 'A' 'I' 'o' 'u' work incorrectly

### ISSUE THREAD

**Issue by BBHNation** [XVimProject/XVim2#182]
Some bugs show in the latest release of Xcode(Xcode10 GM).
Like: 
1. the highlight cursor not show.
2. 'dd' not work, just brew cursor to the front of the line.
3. 'A' 'i' 'o' work incorrectly.
4. 'u' doesn't work.

Please help.

**Comment by pebble8888** [comment]
Write branch name you use.

**Comment by BBHNation** [comment]
@pebble8888 branch is master, for Xcode 10 GM. I clone it from the terminal

**Comment by pebble8888** [comment]
Check #155 and pull master branch.
