### ISSUE TITLE
cannot install for Xcode 10: unsealed contents present in the bundle root

### ISSUE THREAD

**Issue by abbood** [XVimProject/XVim2#187]
I tried to install XVim for Xcode 10. I first searched for my certificate:

```
$ security find-certificate
keychain: "/Users/***/Library/Keychains/login.keychain-db"
version: 512
class: 0x80001000
attributes:
    "alis"<blob>="iPhone Developer: abdullah.bakhach@gmail.com (7gwxb5ja52)"
  ...
abdullah@Abdullahs-MacBook-Pro-2:~$ sudo codesign -f -s "iPhone Developer: abdullah.bakhach@gmail.com (7gwxb5ja52)" /Applications/Xcode.app
Password:
/Applications/Xcode.app: replacing existing signature
/Applications/Xcode.app: unsealed contents present in the bundle root
```

I never got that second line before. And now when I restart Xcode Xvim simply isn't installed. Advice?

**Comment by pebble8888** [comment]
I think `security find-certificate` command has nothing to do with XVim.

**Comment by abbood** [comment]
@pebble8888 sure it does, see https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by abbood** [comment]
@pebble8888 I tried the same syntax as the link you sent.. I'm getting the same error
```
sudo codesign -f -s XcodeSigner /Applications/Xcode.app
Password:
/Applications/Xcode.app: replacing existing signature
/Applications/Xcode.app: unsealed contents present in the bundle root
```

**Comment by FrizzleFur** [comment]
I fixed it by the guide of this [记：在 Xcode 10 中安装 XVim2 - 风萧萧](https://note.wuze.me/xvim2)

1. create a certificate by your keychains， .eg  XcodeSigner
![](https://i.loli.net/2019/01/14/5c3c22e002296.jpg)
2. resign xcode 10

```
# XcodeSigner  is the name of  certificate you created
sudo codesign -f -s XcodeSigner /Applications/Xcode.app 
```
3. waiting 。。。。

4.  reinstall XVim2

5. open xcode, Load Bundle

**Comment by nyan-lin-tun** [comment]
> I fixed it by the guide of this [记：在 Xcode 10 中安装 XVim2 - 风萧萧](https://note.wuze.me/xvim2)
> 
> 1. create a certificate by your keychains， .eg  XcodeSigner
>    ![](https://camo.githubusercontent.com/b80fbab58311d6f1f83b29abcd9dd122a5f95492/68747470733a2f2f692e6c6f6c692e6e65742f323031392f30312f31342f356333633232653030323239362e6a7067)
> 2. resign xcode 10
> 
> ```
> # XcodeSigner  is the name of  certificate you created
> sudo codesign -f -s XcodeSigner /Applications/Xcode.app 
> ```
> 1. waiting 。。。。
> 2. reinstall XVim2
> 3. open xcode, Load Bundle

Showing 

Password:
/Applications/Xcode.app/: replacing existing signature
/Applications/Xcode.app/: unsealed contents present in the bundle root

after resigning Xcode.

**Comment by pebble8888** [comment]
close for old issue.
