### ISSUE TITLE
xcode 10 issue

### ISSUE THREAD

**Issue by BetrayalPromise** [XVimProject/XVim2#188]
/Library/Developer/CommandLineTools/../Info, CFBundleShortVersionString) does not exist

**Comment by pebble8888** [comment]
I can't understand what you say.
Write detail.

**Comment by yingmu52** [comment]
confirmed working on Xcode Version 10.0 (10A255)

**Comment by BetrayalPromise** [comment]
YES Version 10.0 (10A255)

**Comment by lneoe** [comment]
`sudo xcode-select -r` 
this works for me
