### ISSUE TITLE
Status line turns black when Xcode loses focus

### ISSUE THREAD

**Issue by rikchilvers** [XVimProject/XVim2#19]
Normally, the status line is grey. When another app gains focus, the line becomes black for the current tab. Switching between tabs in Xcode makes the line grey again.

**Comment by antmd** [comment]
The XVim command-line could do with a re-write. However, the current behaviour is expected, and managed by the OS: the bar uses an NSVisualEffectsView, which automatically changes colour depending on the focus state of it's parent window.
