### ISSUE TITLE
Cannot install XVim2 on Xcode 10.0

### ISSUE THREAD

**Issue by BITPZY** [XVimProject/XVim2#193]
I installed XVim2 on my Xcode 10.0(10A255), Macbook Pro(macOS High Sierra v10.13.6). 
The original location pointed by the points is: /Library/....... So, I firstly changed my points to this location: /Applications/Xcode.app/Contents/Developer. 
After I execute the "make" command, there is a sentence "BUILD SUCCEEDED" on my terminal. 
So, I thought I installed the plugin successfully.
When I reopened my Xcode, there was no indication that whether or not to add the plugin.
Anyone has this problem on Xcode 10.0?
Thanks for helping me.

**Comment by vitket** [comment]
Try 4 point from this:  https://github.com/XVimProject/XVim

**Comment by ChrisRyuGS** [comment]
> Try 4 point from this: https://github.com/XVimProject/XVim

I have same issue.
`defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-10.0`
is not work for me.

**Comment by honghaoli** [comment]
Same issue here.
`defaults delete...
`
not working.

When I open Xcode, it asked me if I want to use this Xvim bundle.
Even if I clicked "Load bundle", the plugin does not work, as if it were not installed.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/5935909/47275480-c6968800-d564-11e8-9877-fa158855f338.png">

**Comment by honghaoli** [comment]
Same issue here.
`defaults delete...
`
not working.

When I open Xcode, it asked me if I want to use this Xvim bundle.
Even if I clicked "Load bundle", the plugin does not work, as if it were not installed.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/5935909/47275480-c6968800-d564-11e8-9877-fa158855f338.png">

**Comment by honghaoli** [comment]
same issue.

**Comment by andres-blanco** [comment]
Did you try resigning xcode? https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by honghaoli** [comment]
resigning xcode works for me, thanks!

**Comment by BITPZY** [comment]
> Try 4 point from this: https://github.com/XVimProject/XVim

Thanks. It works for me. However, I want to mention that when I execute the command, the terminal says it doesn't find the file. Anyway, it works.
