### ISSUE TITLE
Cursor skips multiple lines

### ISSUE THREAD

**Issue by rikchilvers** [XVimProject/XVim2#20]
After transitioning from Insert -> Normal mode, the cursor will skip multiple lines when pressing j.

![skips lines](https://user-images.githubusercontent.com/583534/31466820-7490d788-aed0-11e7-9bdd-271b6f9ea8f5.gif)

As far as I can tell this only happens at the bottom of a file, but I haven't done hugely extensive testing.

**Comment by rikchilvers** [comment]
Brief follow-up: this can happen anywhere in the file.

**Comment by pebble8888** [comment]
I can't reproduce it.
Please reopen if you have an problem.
