### ISSUE TITLE
Build Failed - Error 65 - changes each time

### ISSUE THREAD

**Issue by ryans-git** [XVimProject/XVim2#206]
Xcode 10.1 (I tried on 9 a long time ago and could never build that either actually)
commit: 3b07505cb4fd52cd16a571fd7bdb54106a5653e3

Can never get it to compile. I have tried deleting & recreating the certificate, deleting & re cloning the repo, make clean/uninstall, sudo make (builds but doesn't work)

The error changes everytime too. Latest one after a clean is:
```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/myusername/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/x86_64/SourceCodeEditorViewProxy.o /Users/myusername/XVim2/XVim2/Xcode/SourceCodeEditorViewProxy.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [release] Error 65
```

Along with others...
```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/myusername/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/x86_64/XVimHistoryHandler.o /Users/myusername/XVim2/XVim2/XVim/XVimHistoryHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [release] Error 65

.....

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/myusername/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/x86_64/XVimMarkSetEvaluator.o /Users/myusername/XVim2/XVim2/XVim/Evaluator/Argument/XVimMarkSetEvaluator.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [release] Error 65

.....

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/myusername/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/x86_64/NSAttributedString+Geometrics.o /Users/myusername/XVim2/XVim2/Helper/NSAttributedString+Geometrics.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/myusername/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/x86_64/XVimHistoryHandler.o /Users/myusername/XVim2/XVim2/XVim/XVimHistoryHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/myusername/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/x86_64/XVimZEvaluator.o /Users/myusername/XVim2/XVim2/XVim/Evaluator/MotionArgument/XVimZEvaluator.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
make: *** [release] Error 65
```
Build log [gist](https://gist.github.com/ryans-git/25ccb0829f776a07814551709273a3ca)

**EDIT**: I would assume the problem is:
`error: can't exec '/usr/bin/gcc-4.0' (No such file or directory)`
I can't figure out how to symlink it to gcc with the apple /usr/bin protection. The location for gcc is
```
$ which gcc
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc
```

So I linked: gcc-4.0 -> gcc in that Xcode directory, but still doesn't work. Get the same "error: can't exec '/usr/bin/gcc-4.0' (No such file or directory)"

**Comment by phuongzzz** [comment]
have you found the solution of this issue? :(

**Comment by coderli01** [comment]
same issue. 
I try to upgrade Xcode to 10.2, and found some issue in compiling my project, and went back to Xcode 10.1. 

And found similar issue.

`
xcodebuild -configuration Release
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'XVim2')
`

**Comment by coderli01** [comment]
update:
macOS: 10.14.3
Xcode: ver 10.1

Here is my solution
1. git clone project, and open it with Xcode.
2. Build Settings -> Swift Language Setting chose Swift 4.2 
![image](https://user-images.githubusercontent.com/33228104/55526857-27f08480-56c9-11e9-85f1-eaa13c791fee.png)
3. Build this project again.
4. open terminal, and `make`
Done~

**Comment by pebble8888** [comment]
close for old issue.
