### ISSUE TITLE
Yanking overwrites whatever the last register was.

### ISSUE THREAD

**Issue by mcsimenc** [XVimProject/XVim2#214]
Hi, I reported this with the XVim1 repository issues. Oops. 
https://github.com/XVimProject/XVim/issues/1102

# Description
Yanking overwrites whatever last used register was

# Operation
If I yank to register a, then yank to register b, then put register a to replace string C, then register a will have C and b will remain unchanged.

# Expected behaviour
When putting a register's contents, whatever gets replaced should go into the default register but not the specific register used. At least that's the default behavior in my version of Vim.

# Environments
  - Xcode Version [10.1+ ]
  - XVim branch and revision [XVim2 revision : 5c7aaa56e2d39ed2dd9ad42b7f14e4c91ee59218
OS Version : Version 10.14 (Build 18A391)
Xcode Version : 10.1]
  - Keyboard Language [English]
  - Input source language [English]

**Comment by dhasl002** [comment]
I would like to contribute. I will start with this issue.

**Comment by hyouuu** [comment]
Thanks @dhasl002 - this will be really helpful!!

**Comment by dylanhand** [comment]
Hi @pebble8888 - can this issue be closed? 

It looks like this has been fixed and merged.

**Comment by pebble8888** [comment]
It can be closed.
Thanks.
