### ISSUE TITLE
Visual block mode plus d or x equals extra characters deleted

### ISSUE THREAD

**Issue by mcsimenc** [XVimProject/XVim2#216]
# Description
When in visual block mode, if deleted, extra characters are removed.

# Operation
From the start of the last line of the text below,
`<C-v> 10 j k d`

# Expected behaviour
Two columns of text should be deleted. Instead, sometimes one or two extra characters are removed. Here is the text I am using,
```
//Seqdesc ::= user {
//    type str "Submission",
//    data {
//        {
//            label str "AdditionalComment",
//            data str "ALT EMAIL:primary@email.com"
//        }
//    }
//}
//Seqdesc ::= user {
//    type str "Submission",
//    data {
//        {
//            label str "AdditionalComment",
//            data str "Submission Title:None"
//        }
//    }
//}
```

# Environments
  - Xcode Version [10.1+ ]
  - XVim branch and revision [XVim2 revision : 5c7aaa56e2d39ed2dd9ad42b7f14e4c91ee59218
OS Version : Version 10.14 (Build 18A391)
Xcode Version : 10.1]
  - Keyboard Language [English]
  - Input source language [English]

Thanks!

**Comment by squarefrog** [comment]
I get the same with change `c`. For example:

    //abcdef
    //defghi

Place cursor on `a`. `<C-v> j l`

Expected:

    //cdef
    //fghi

Observed:

    //ef
    //fghi

**Comment by jstarschuyler** [comment]
I have also seen this behavior in XCode 10. I have also noticed that when I undo the block delete that removed extra characters, the block selector will highlight the portions that were deleted that I did not select previously.

**Comment by squarefrog** [comment]
A workaround for now would be to use the built-in support for multiple cursors:
https://stackoverflow.com/a/50697236/816002

**Comment by jstarschuyler** [comment]
Honestly, and I mean no disrespect to the developers of this project, but I have had so many issues with this and the older XVim plugin that my workaround was to just switch to VS Code and use their plugins.

**Comment by mcsimenc** [comment]
Hi jstar, if you have free time please feel free to jump in to this open-source project and help us out by fixing some bugs :)

**Comment by jstarschuyler** [comment]
Fair enough and I apologize if I came off a little strong there. I will say XCode's plugin system seems like a royal pain to work with so I can't imagine what you all have been through to get it going this far.

**Comment by mcsimenc** [comment]
Thanks for the tip about VS Code. I am totally habituated to Vim keybindings so good to learn about alternatives. Not everyone feels the same about Vim...My friend once (proudly) lamented to me that he wrote his entire PhD dissertation in the early 80s with Vi. I was like, niiiiice.

**Comment by chml** [comment]
I have a PR for this: https://github.com/XVimProject/XVim2/pull/222

**Comment by pebble8888** [comment]
FYI #155
visual pass:31 fail:24

Visual block feature is almost dead sadly.

**Comment by pebble8888** [comment]
@chml 
Thank you for your PR.

It' merged to `master` branch.
