### ISSUE TITLE
Xcode 10.2 crashes on macOS 10.14.4 

### ISSUE THREAD

**Issue by iMcG33k** [XVimProject/XVim2#231]
I deleted . xvimrc file before install xvim2

Here's the macOS crash report:

> Process:               Xcode [19380]
> Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
> Identifier:            com.apple.dt.Xcode
> Version:               ???
> Build Info:            IDEFrameworks-14490120000000000~2
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Xcode [19380]
> User ID:               501
> 
> PlugIn Path:             
> PlugIn Identifier:       
> PlugIn Version:          ??? (655.1.1)
> 
> Date/Time:             2019-04-22 13:30:39.836 +0800
> OS Version:            Mac OS X 10.14.4 (18E226)
> Report Version:        12
> Anonymous UUID:        A0D8CF94-5C6C-92F9-F419-AA408DC5B66B
> 
> 
> Time Awake Since Boot: 510000 seconds
> 
> System Integrity Protection: disabled
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_CRASH (Code Signature Invalid)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    Namespace CODESIGNING, Code 0x1
> 
> kernel messages:
> 
> VM Regions Near 0 (cr2):
> --> 
>     __TEXT                 000000010b0c3000-000000010b0c6000 [   12K] r-x/rwx SM=COW  
> 
> Thread 0 Crashed:
> 0                                 	0x0000000114f8f000 _dyld_start + 0
> 
> Thread 0 crashed with X86 Thread State (64-bit):
>   rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
>   rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee4b3cbe0
>    r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
>   r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
>   rip: 0x0000000114f8f000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
>   
> Logical CPU:     0
> Error Code:      0x00000000
> Trap Number:     0
> 
> 
> Binary Images:
>        0x10b0c3000 -        0x10b0c5ff7 + (14490.120) <1725EDE6-60B2-3B7C-AFA0-BFF2E4F50AF0> 
>        0x114f8e000 -        0x114ff86ef + (655.1.1) <F217F7F8-A795-3109-B77F-B1E2277F3E3B> 
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 21525868
>     thread_create: 0
>     thread_set_state: 0
> 
> VM Region Summary:
> ReadOnly portion of Libraries: Total=624K resident=0K(0%) swapped_out_or_unallocated=624K(100%)
> Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
>  
>                                 VIRTUAL   REGION 
> REGION TYPE                        SIZE    COUNT (non-coalesced) 
> ===========                     =======  ======= 
> STACK GUARD                       56.0M        1 
> Stack                             8192K        1 
> __DATA                             232K        3 
> __LINKEDIT                         184K        2 
> __TEXT                             440K        2 
> shared memory                        8K        2 
> ===========                     =======  ======= 
> TOTAL                             64.8M       11 
> 
> Model: iMac16,2, BootROM 225.0.0.0.0, 4 processors, Intel Core i5, 2.8 GHz, 8 GB, SMC 2.32f20
> Graphics: kHW_IntelIrisPro6200Item, Intel Iris Pro Graphics 6200, spdisplays_builtin
> Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5544
> Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5544
> AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x156), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
> Bluetooth: Version 6.0.11f4, 3 services, 27 devices, 1 incoming serial ports
> Network Service: Ethernet, Ethernet, en0
> Serial ATA Device: KINGSTON SUV400S37240G, 240.06 GB
> USB Device: USB 3.0 Bus
> USB Device: VLI Product String
> USB Device: Bluetooth USB Host Controller
> USB Device: FaceTime HD Camera (Built-in)
> USB Device: Hub
> USB Device: HHKB Professional
> Thunderbolt Bus: iMac, Apple Inc., 27.4

**Comment by pebble8888** [comment]
It' not related to XVim plugin.

**Comment by iMcG33k** [comment]
> It' not related to XVim plugin.

Sorry for bothering you. I forgot that my certification was Expired...
