### ISSUE TITLE
XVim2 not working  in xcode 10.2.1 & os 10.14.4 (18E226).

### ISSUE THREAD

**Issue by RobberJJ** [XVimProject/XVim2#232]
XVim2 not working  in xcode 10.2.1 & os 10.14.4 (18E226).

**Comment by W-quan** [comment]
+1

**Comment by schu34** [comment]
I'm able to build/install fine and movement seems to be working but I'm seeing these issues
1. `J` commands aren't working at all,
2. `O`/`o` commands are pulling the last character on the previous line onto the next line 

for example, if I'm on a line that looks like this:
```
aaa
```
in normal mode and press `o`, I end up with 

```
aa
a
```

3. `A` commands are putting me into insert mode *before* the last character of the line, instead of after it. 
 
4. Selecting with visual mode and then yanking causes Xcode to crash. For some reason, I can't get Xcode to show the stack trace after it crashes any more but when it did I saw something about trying to get a substring where the start and end values passed in were near max int.

**Comment by michaelplutovr** [comment]
these issues are not fixed for me on develop, i get the same behavior

**Comment by devapps19** [comment]
Tried 5/11/19 and still not work on either Master or Develop branch

**Comment by gaoyuqiang** [comment]
Is it working now?

**Comment by pebble8888** [comment]
I can't reproduce it.
56c8b54
macOS 10.14.5 MacBookPro 2017

**Comment by msvbg** [comment]
FWIW the master branch works just fine for me with the latest Xcode.

**Comment by gaoyuqiang** [comment]
> FWIW the master branch works just fine for me with the latest Xcode.

thank you!  Master branch works for me too!  xcode10.2.1 & macos 10.14.5

**Comment by Luyakus** [comment]
why not works for me  😂, xocde 10.2, macOS 10.14.4

**Comment by yeonsh** [comment]
Same here. Not working on Xcode 10.2.1 and macOS 10.14.4. :(

**Comment by yeonsh** [comment]
It works after updating macOS to 10.14.5. :)

**Comment by mf3r1** [comment]
XVim2 not working for me on Xcode 10.2.1, Mojave 10.14.5, MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)

What I have tried: 
-Recreate XcodeSigner (Trust it)
-Resign Xcode with it
-I have tried Xvim2 with develop and master branches
-I have done make command with sudo make 
-I removed the xvimrc which could cause issues (for me at least)
No effect :(

**Comment by yeonsh** [comment]
After upgrading to macOS 10.14.5 here is what I did:

- codesign Xcode with XcodeSigner again and waited until finish
- build Xvim2 on master branch. (normal user not using sudo)
- execute Xcode (not sure it asked about XVim2 this time) and quit
- execute Xcode

**Comment by mf3r1** [comment]
Thanks @yeonsh for the quick answer. It is working now. 
Problem was that I used sudo as you mentioned before. So for the record...

1. clone Xvim2 
2. go to the Xvim2 folder. In case you not deleted Xvim2 previously... (run make uninstall)
3. resign the XcodeSigner (it is not needed to be trusted) https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md
4. cd to the Xvim2 folder
5. run make without sudo . 

(I did the whole process with 

- Xcode 10.2.1 
- Mojave 10.14.5 
- MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) 
- with OhMyZsh 
- from the standard Terminal 
- on the master branch

(Pro tip, remove the xvimrc file, and if anything came up... try the develop branch and the tags as well)

**Comment by michaelplutovr** [comment]
Well, this was user error all the way on my part :X I forgot to self sign Xcode on the laptop I was using.

**Comment by HaiyuanZh** [comment]
> Thanks @yeonsh for the quick answer. It is working now.
> Problem was that I used sudo as you mentioned before. So for the record...
> 
> 1. clone Xvim2
> 2. go to the Xvim2 folder. In case you not deleted Xvim2 previously... (run make uninstall)
> 3. resign the XcodeSigner (it is not needed to be trusted) https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md
> 4. cd to the Xvim2 folder
> 5. run make without sudo .
> 
> (I did the whole process with
> 
> * Xcode 10.2.1
> * Mojave 10.14.5
> * MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
> * with OhMyZsh
> * from the standard Terminal
> * on the master branch
> 
> (Pro tip, remove the xvimrc file, and if anything came up... try the develop branch and the tags as well)

Thanks   mf3r1 buddy, it works now. :)

**Comment by TravisCao** [comment]
> > Thanks @yeonsh for the quick answer. It is working now.
> > Problem was that I used sudo as you mentioned before. So for the record...
> > 
> > 1. clone Xvim2
> > 2. go to the Xvim2 folder. In case you not deleted Xvim2 previously... (run make uninstall)
> > 3. resign the XcodeSigner (it is not needed to be trusted) https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md
> > 4. cd to the Xvim2 folder
> > 5. run make without sudo .
> > 
> > (I did the whole process with
> > 
> > * Xcode 10.2.1
> > * Mojave 10.14.5
> > * MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
> > * with OhMyZsh
> > * from the standard Terminal
> > * on the master branch
> > 
> > (Pro tip, remove the xvimrc file, and if anything came up... try the develop branch and the tags as well)
> 
> Thanks mf3r1 buddy, it works now. :)

What version of swift are you using? I followed your instrctions but it printed the output like this.
![image](https://user-images.githubusercontent.com/35266867/58762928-9053c900-8587-11e9-981d-a7653ad35eb9.png)

**Comment by RobberJJ** [comment]
> Thanks @yeonsh for the quick answer. It is working now.
> Problem was that I used sudo as you mentioned before. So for the record...
> 
> 1. clone Xvim2
> 2. go to the Xvim2 folder. In case you not deleted Xvim2 previously... (run make uninstall)
> 3. resign the XcodeSigner (it is not needed to be trusted) https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md
> 4. cd to the Xvim2 folder
> 5. run make without sudo .
> 
> (I did the whole process with
> 
> * Xcode 10.2.1
> * Mojave 10.14.5
> * MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
> * with OhMyZsh
> * from the standard Terminal
> * on the master branch
> 
> (Pro tip, remove the xvimrc file, and if anything came up... try the develop branch and the tags as well)

It worked this way, and I felt it was important to replace the certificate. 
The Step 3:resign the XcodeSigner (it is not needed to be trusted) https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by MatoMA** [comment]
It would be nice to add a resign reminder in the project's README. I found that every time Xcode update, this kind of issues rise  😂

**Comment by yingmu52** [comment]
confirmed working on `Version 10.2.1 (10E1001)`

**Comment by pebble8888** [comment]
close for old issue
