### ISSUE TITLE
XCode 10.2.1: The shortcut key (Add Documentation -- Alt+CMD+\) is broken.

### ISSUE THREAD

**Issue by RobberJJ** [XVimProject/XVim2#235]
XCode 10.2.1: The shortcut key (Add Documentation -- **`Alt+CMD+\`**) is broken. Mac OS Mojave 10.14.5.

**Comment by pebble8888** [comment]
Not related to XVim.

Try this.
1. Close xcode.
2. `sudo /usr/libexec/xpccachectl`
3. Restart macOS.

**Comment by RobberJJ** [comment]
It Works after the restart.

**Comment by RobberJJ** [comment]
> Not related to XVim.
> 
> Try this.
> 
> 1. Close xcode.
> 2. `sudo /usr/libexec/xpccachectl`
> 3. Restart macOS.

It Works after the restart.
