### ISSUE TITLE
Xcode 11

### ISSUE THREAD

**Issue by michaeleisel** [XVimProject/XVim2#236]
What is the current state of support for Xcode 11?

**Comment by pebble8888** [comment]
I’ll check it after downloading xcode. Yet not done.

**Comment by ashchan** [comment]
Just tried on macOS 10.15 Beta, `make` failed with this (other log stripped):

```
XVim2/XVim2/Xcode/SourceCodeEditorViewWrapper.s:57:12: error: unexpected token in argument list
    andq $0FFFFFFFFFFFFFFF0H, %rsp
           ^
Command CompileC failed with a nonzero exit code
```

**Comment by pebble8888** [comment]
Xcode11 on macOS11.14.5

`develop` branch

UnitTest Summay
480 Passing Tests
62 Faling Tests

**Comment by ashchan** [comment]
The updated `develop` branch runs good on both Xcode 10.2 and 11 now (on macOS 10.15).

**Comment by b-raines** [comment]
Looks like Bountysource is for XVim repo, not XVim2.. otherwise I'd put a bounty on this.

**Comment by sebbo176** [comment]
The develop branch works well on Xcode 11 Beta (11M336w) in Catalina

**Comment by the-real-adammork** [comment]
`develop` branch works well on Xcode 11.0 beta 4 (11M374r) & Mojave 10.14.5 (18F203)

**Comment by ckitterl** [comment]
After Appstore auto updated my xcode to 11.0, my xvim2 have not worked yet. I try to pull the develop version( **8b32b4**) and reinstall but not work.
Do I miss something?

xcode version: 11.0 (11A420a)
system: 10.14.5 (18F132)

**Comment by marktrobinson** [comment]
I got make to work from develop and "Load Bundle" to appear but it actually doesn't work even after all that.  Not sure why

**Comment by escakot** [comment]
Try checking "xcode-select -p". The path somehow changed after the update, first time this has ever happened to me. Follow all the steps accordingly and it should work fine. 

> After Appstore auto updated my xcode to 11.0, my xvim2 have not worked yet. I try to pull the develop branch( **8b32b4**) and reinstall but not work.
> Do I miss something?
> 
> xcode version: 11.0 (11A420a)
> system: 10.14.5 (18F132)

**Comment by marktrobinson** [comment]
Has anyone else noticed undo not behaving correctly? It undos more than one step for me

**Comment by ckitterl** [comment]
@escakot I have two mac computer with two version of xcode. These xcode's path are the same  —— **/Applications/Xcode.app/Contents/Developer**

Old xcode version is 10.2.1 (10E1001) and xvim works well; But another xcode 11.0(11A420a) failed.

**Comment by escakot** [comment]
@ckitterl Try Code Signing Xcode after make. This has worked a couple of times for me when it doesn't ask to load the XVim plugin.

XCode 11.0 (11A420a)
MacOS Mojave (10.14.4)

> @escakot I have two mac computer with two version of xcode. These xcode's path are the same —— **/Applications/Xcode.app/Contents/Developer**
> 
> Old xcode version is 10.2.1 (10E1001) and xvim works well; But another xcode 11.0(11A420a) failed.

**Comment by externvoid** [comment]
The develop branch works fine below environment.
Xcode 11.1
Mojave 10.14.6
Under shift-V, Visual Selection Mode, the cursor can move correctly.

**Comment by jackzhhuang** [comment]
> The develop branch works fine under below environment.
> Xcode 11.1
> Mojave 10.14.6
> Under shift-V, Visual Selection Mode, the cursor can move correctly.

Hi, can you tell me how you installed on Xcode 11.1, Mojave 10.14.6?
I tried following the instructions.
Though it asked me to load the XVim it did not work.

**Comment by the-real-adammork** [comment]
> > The develop branch works fine under below environment.
> > Xcode 11.1
> > Mojave 10.14.6
> > Under shift-V, Visual Selection Mode, the cursor can move correctly.
> 
> Hi, can you tell me how you installed on Xcode 11.1, Mojave 10.14.6?
> I tried following the instructions.
> Though it asked me to load the XVim it did not work.


- CodeSign XCode (https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md)
- checkout latest on `develop` branch
- `make`
- Open Xcode, load bundle

**Comment by K77-alt** [comment]
The develop branch works fine under below environment.
Xcode 11.2
Catalina 10.15.1

However, I needed to manually copy XVim2.xcplugin.
(in XVim2 directory)
cp -R build/Release/XVim2.xcplugin /Users/your_username/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins

**Comment by silverhammermba** [comment]
master branch is working well with Xcode 11.3.

This can probably be closed.
