### ISSUE TITLE
SWIFT_VERSION '5.0' is unsupported

### ISSUE THREAD

**Issue by playcode001** [XVimProject/XVim2#237]
SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'XVim2')
![image](https://user-images.githubusercontent.com/5078044/59007008-39841300-8857-11e9-8a40-9088905fa388.png)

**Comment by neivin** [comment]
Same issue here:
```neivin:~/source$ swift --version
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0```

**Comment by pebble8888** [comment]
Please read README.md and write branch name and Xcode version.

**Comment by hnguyen94** [comment]
Same issue on master/develop branch with Xcode 10.1

**Comment by sashaweiss** [comment]
Any updates on this? Also running into this.

**Comment by sashaweiss** [comment]
I suspect this is related to the fact that I had Xcode 10.1 - upgrading _should_ fix this issue?

**Comment by pebble8888** [comment]
`master/develop` branch doesn't support xcode10.1.

Please use `xcode10.1` tag for Xcode10.1.
