### ISSUE TITLE
Xcode 11 - Visual Selection View

### ISSUE THREAD

**Issue by ryantstone** [XVimProject/XVim2#238]
Cursor navigation works fine except in visual mode, when switch to visual mode the selection cursor stays but does not show movement or which lines are being highlighted. Then if I tap X to delete the lines I'm intending to delete they are deleted. So it seems in the background that the cursor is moving properly but not being translated to the screen.

Mac 10.14.5
XCode 11.0 Beta 1

**Comment by pebble8888** [comment]
The visual line feature needs fix for xcode11.

**Comment by pebble8888** [comment]
Can somebody check it in macOS 10.15?

**Comment by kuglee** [comment]
It's the same in macOS 10.15.

**Comment by pebble8888** [comment]
@kullee
Thank you.

This is a selection redrawing problem that needs a high skill swift reverse engineering IMHO.
I'm sorry that the bug is too difficult to fix for me.

**Comment by pebble8888** [comment]
FIxed. #240
