### ISSUE TITLE
Weird undo behavior in Xcode 11 beta 2

### ISSUE THREAD

**Issue by timothycosta** [XVimProject/XVim2#242]
Using Xcode 11 beta 2 today I've had numerous serious issues with undo.  Several times I've hit `u` and gotten jumped back *far* in the file's history.  After, hitting `r` sometimes works, but sometimes changes have been completely lost.

**Comment by pebble8888** [comment]
I can't investigate for insufficient information.
Please write sufficient information that anyone can reproduce.

**Comment by timothycosta** [comment]
I actually mostly posted this as a PSA to other users of the beta since it could lead to lost work.  Thankfully the issue hasn't occurred again since the first day I installed beta 2.  I'll reopen this if I find a consistent way to reproduce it.
