### ISSUE TITLE
Not work in Xcode 10.3

### ISSUE THREAD

**Issue by kimtaewoo** [XVimProject/XVim2#244]
I have updated Xcode to version 10.3(10G8) on macOS Mojave version 10.14.6.
Master and develop branch of XVim2 both did not work. Is this because of the Xcode?

**Comment by escakot** [comment]
I'm using Xcode version 10.3. MacOS Mojave version 10.14.4.
It works using master branch.

I codesigned xcode after the xcode 10.3 update and made the latest master branch. It asked to load the Vim Bundle but it wasn't working. I codesigned xcode again and it worked after that.

@kimtaewoo, try to [codesign Xcode](https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md) again after make.

**Comment by kimtaewoo** [comment]
> I'm using Xcode version 10.3. MacOS Mojave version 10.14.4.
> It works using master branch.
> 
> I codesigned xcode after the xcode 10.3 update and made the latest master branch. It asked to load the Vim Bundle but it wasn't working. I codesigned xcode again and it worked after that.
> 
> @kimtaewoo, try to [codesign Xcode](https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md) again after make.

@escakot, Thank you so much!
Even though the previous codesign was not over yet, it did not work. After creating a new one, it works very well!
