### ISSUE TITLE
xvim2 can't be installed in xcode 10.3

### ISSUE THREAD

**Issue by codermite** [XVimProject/XVim2#246]
I try to install the xvim with my Xcode which the version is 10.3. it didn't even when I click the load bundle. I checked the version with xvim. xvim's tag version  is 10.3! why i didn't install it successful. if I have install it successful where I can change the model between vim and default input model. the button where is it?

**Comment by externvoid** [comment]
try XVim2 of the develop branch.

**Comment by codermite** [comment]
It doesn't work. My mac OS version is 10.15 Beta (19A536g).  no any error prompt info

**Comment by externvoid** [comment]
Did you do with following ways?

```
>git clone https://github.com/XVimProject/XVim2.git
> git tag
xcode10.1
xcode10.2
xcode10.3
xcode9.2
xcode9.3
xcode9.4
>git checkout xcode10.3
```

**Comment by Adolf-L** [comment]
@externvoid  yes, I did the steps as you show me. when execute "make" the terminal window show me "build success" then I open Xcode, click "loading bundle", but it is nothing happened. that's all!

**Comment by externvoid** [comment]
I actually compiled two XVim2 sources which are the master branch and the develop branch.  And I found out the following. 
1. The master branch with xcocd10.3 tag can be compiled successfully, but unfortunately Xcode 10.3 under macOS Mojave 10.14.6 can not load the plugin.

```
~/.doc/work/XVim2:500> swift -v
2019-08-30 14:20:49.139 xcodebuild[45074:11949019] WARNING: Failed to load plugin at path: "/Users/tanaka/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/xxx/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
(The rest is omitted.)
```

2. The develop branch can be also compiled. And Xcode 10.3 under macOS same above can load the plugin, then the plugin's jklh cursor movement function can be enabled.

**Comment by weihu120** [comment]
### try the commands bellow, it have beed working for me:
>> **git clone https://github.com/XVimProject/XVim2.git
git clone https://github.com/slegetank/ResignXcode.git
cd ResignXcode
python3 ResignXcode.py
cd ../XVim2
make**

**Comment by externvoid** [comment]
I notice that `develop` branch seemed to work well but in the visual mode the cursor disappeared. The I tried 10.2 tag, which works well so far.

**Comment by ksteigerwald** [comment]
I am having the same issue. 

<unknown>:0: error: Swift does not support the SDK 'MacOSX10.13.sdk'
and
The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(1 failure)
make: *** [release] Error 65

**Comment by perfectspr** [comment]
Have you resigned your Xcode?  https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md
It works well for me.

**Comment by ksteigerwald** [comment]
@perfectspr yes, multiple times.

**Comment by hggz** [comment]
It's working for me on the latest GM seed 2 of Xcode 11. Thanks again guys. Another year, another trip down to the Xvim repo 🍾

**Comment by ksteigerwald** [comment]
After install/uninstall multiple versions, I am able to get the make complete successfully. When XCode loads it ask if I want to load the bundler, I hit load. I go into XCode and the vim commands do not take.

**Comment by pebble8888** [comment]
close for old issue
