### ISSUE TITLE
Visual selection not displaying...

### ISSUE THREAD

**Issue by patniemeyer** [XVimProject/XVim2#247]
I notice that hitting v-cursor movement is no longer highlighting the visually selected lines.  The selection is there, just not displayed.

I am running the developer branch latest on 10.14.6 with xcode 10.2.1.

thanks!

**Comment by pebble8888** [comment]
Please use appropriate tag for your Xcode version.
`develop` branch is for Xcode 11 beta.
Use tag `xcode10.2`

**Comment by externvoid** [comment]
I encounter the situation same above running with `develop` branch on 10.14.6 with Xcode10.3. In the visual mode, the cursor was not be able to be moved. Then, I tried two tag 10.3 and 10.2 so things below were found out.

1. With 10.3 tag, Xcode10.3 didn't load the plugin and the vim functionality indeed coundn't be used.

2. With 10.2 tag, Xcode10.2 did load the plugin successfully and displayed the load bundle or skip bundle dialog panel.

**Comment by MasterBeta** [comment]
> I encounter the situation same above running with `develop` branch on 10.14.6 with Xcode10.3. In the visual mode, the cursor was not be able to be moved. Then, I tried two tag xcode10.3 and xcode10.2 so things below were found out.
> 
> 1. With xcode10.3 tag, Xcode10.3 didn't load the plugin and the vim functionality indeed coundn't be used.
> 2. With xcode10.2 tag, Xcode10.3 did load the plugin successfully and displayed the load bundle or skip bundle dialog panel.

 xcode10.3 tag works for me. Try resigning the Xcode.

**Comment by LaurentHBrunet** [comment]
I'm encountering this issue with Xcode Version 11.0 (11A420a), using the current develop branch.

**Comment by pebble8888** [comment]
I have not experienced it in Xcode11 and macOS10.14.6 and the develop branch 8b32b40.

**Comment by bingosoft** [comment]
in XCode 11 switching to visual mode by 'v' key causes moving of the cursor on 6 symbols to the right, it's almost impossible to select any text in visual mode :(

**Comment by LaurentHBrunet** [comment]
> I have not experienced it in Xcode11 and macOS10.14.6 and the develop branch [8b32b40](https://github.com/XVimProject/XVim2/commit/8b32b4044ef11621977279f82e7933d9cc80b5c1).

You are right, I updated to most recent dev branch and it's now fine. I just missed an update.

**Comment by pebble8888** [comment]
close for old issue.
