### ISSUE TITLE
Xcode default settings delete

### ISSUE THREAD

**Issue by abbasaa** [XVimProject/XVim2#251]
With the latest version of Xcode 11.0, my plugin stopped working. Redid steps and reinstall XVim, but the defaults delete command is not working anymore. 

Message: Domain (com.apple.dt.Xcode) not found
Defaults have not been changed.

**Comment by marktrobinson** [comment]
`defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.0` worked for me

**Comment by abbasaa** [comment]
I think the problem was that I had already deleted it so it didn't exist anymore. However, when I finally got asked to load in the XVim plugin, it didn't work.

**Comment by CoderPiF** [comment]
try `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-X.X.X`

`defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.2.1` worked for me
