### ISSUE TITLE
XCode 11: switching to visual mode by 'v' moves cursor to 3...6 symbols to the right

### ISSUE THREAD

**Issue by bingosoft** [XVimProject/XVim2#252]
Recently I compiled **XVim2** for **XCode 11** from branch *develop*

Reproduces only when the code indented with TAB symbol in XCode settings, when indenting by 4 spaces all works fine

**How to reproduce**:

1. Open an empty playground
2. Write a code with TAB idents
```
	var str = "Hello, playground"
	print(str)
```
3. Try to select any code fragment in visual mode by typing 'v' key

**Result**: cursor moves to 3..6 symbols to the right, selecting of the code fragment almost impossible

In Xcode 10.3 worked pretty fine

**Comment by Alex-k-tech** [comment]
I have the same issue for xcode 11.1

**Comment by Alex-k-tech** [comment]
Re-indent file fix my issue 
![image](https://user-images.githubusercontent.com/54838534/67474320-ee7b6880-f65c-11e9-86bd-8a05829624c2.png)

**Comment by davidisaaclee** [comment]
I also have this issue. I noticed that it happens when I use tabs for indentation, and it does not happen when using spaces for indentation (which is probably why @Alex-k-tech's suggestion works for them). It would be nice to be able to continue to use tabs!

**Comment by matejukmar** [comment]
I have same issue in Xcode 12. My tab setting is 3 visual chars for tab. Bot re-indent didn't fix the issue.

**Comment by matejukmar** [comment]
I've created PR that fixes this: https://github.com/XVimProject/XVim2/pull/359

**Comment by bingosoft** [comment]
Thank you, @matejukmar, the solution is really to remove some tab-related logic in `XVim2/XVim/NSTextStorage+VimOperation.m:156`

```
﻿-            if (xvim_sb_peek(sb) == '\t') {
-                col += tabWidth;
-                if (tabWidth)
-                    col -= col % tabWidth;
-            }
-            else {
-                col++;
-            }
+            col++;
```

**Comment by matejukmar** [comment]
@bingosoft yes, I posted another, a bit simpler PR.
