### ISSUE TITLE
Where to place a .vimrc file

### ISSUE THREAD

**Issue by stphnlngdncoding** [XVimProject/XVim2#255]
Hello, I am attempting to remap `jj` to `<Esc>`.  I have created a `.vimrc` file and inserted the text `inoremap jj <Esc>` inside it.  Where do I place this file? Do I need to relaunch or rebuild afterwards?

**Comment by pebble8888** [comment]
https://github.com/XVimProject/XVim2/blob/master/Documents/FeatureList.md#xvimrc

**Comment by pebble8888** [comment]
close an inactive issue.
