### ISSUE TITLE
Will I have to resign and reinstall this plugin each time that Xcodes updates?

### ISSUE THREAD

**Issue by Stormwaker** [XVimProject/XVim2#257]
I've recently started using Xcode and XVim2 along with it. After updating to Xcode 11 I had to reinstall the plugin, this was a big update so I kinda expected that I'll have to reinstall. But today I had to repeat that process with just a small update from Xcode 11 to Xcode 11.1 - will I have to repeat both resigning and reinstalling this plugin each time Xcode updates? Or is there an easier way?

**Comment by the-real-adammork** [comment]
Luckily you only have todo it once for each update. 

macOS obfuscates away the update process from regular users, but its a completely different .app and will need to be unsigned and resigned

**Comment by kjgfcdb** [comment]
I updated my Xcode from 11 to 11.1 today, and found that the Xvim2 didn't work. I tried to rebuild it in `develop` branch, but nothing changed.

**Comment by the-real-adammork** [comment]
did you change the system XCode by using 

```
sudo xcode-select -s /Applications/Xcode.app
```

I usually rename my Xcodes with the version number, so if I just got 11.1 my command would be:

```
sudo xcode-select -s /Applications/Xcode_11.1.app
```

**Comment by r-plus** [comment]
yes for Xcode plugin loading system.

XVim recently support SIMBL plugin loading system, if you choose this way no longer need codesign and rebuild XVim to update Info.plist UDID for every update of Xcode.
