### ISSUE TITLE
The code editor is not effective

### ISSUE THREAD

**Issue by JxbSir** [XVimProject/XVim2#264]
[Write issue description here]
The XVIM is exist in Edit menu, and also enable the plugin, but the code editor is not effective.

```
-------- Debug Info -------
XVim2 revision : 959bf30005d69d12ba06c187cf3c10908effe3f1
OS Version : Version 10.15.1 (Build 19B88)
Xcode Version : 11.2

--- .xvimrc ---
N/A
--------------
```

**Comment by dylanhand** [comment]
Hi @JxbSir! 

Did you make sure to [codesign Xcode](https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md) in step 1 of the install guide?

**Comment by JxbSir** [comment]
Hi @dylanhand 
 
Yes, I did.  I reinstalled it , and it works now

**Comment by dylanhand** [comment]
@JxbSir Great, glad you got it working 👍
