### ISSUE TITLE
Crash when press 'p' or 'P' to paste in xcode 11.1

### ISSUE THREAD

**Issue by evamango** [XVimProject/XVim2#267]
- I use the newest version of branch 'develop'
- Just press 'p' or 'P', Xcode will crash
- Other vim func is OK

**Comment by evamango** [comment]
[crash_info.txt](https://github.com/XVimProject/XVim2/files/3856726/crash_info.txt)
 Here is the crash info. THX!!

**Comment by pebble8888** [comment]
I can't reproduce the crash. 
7467851
Xcode 11.2.1
macOS 10.14.6

**Comment by evamango** [comment]
> I can't reproduce the crash.
> [7467851](https://github.com/XVimProject/XVim2/commit/74678519e4e5d787dca28d5602986c7f8c09ef80)
> Xcode 11.2.1
> macOS 10.14.6

OK, I remap the p/P to others to fix it temporary in .xvimrc.

I remember it works well last month. Orz...

**Comment by pebble8888** [comment]
#281 related
