### ISSUE TITLE
[Xcode11.3] compilation failed - unexpected token

### ISSUE THREAD

**Issue by JaviOverflow** [XVimProject/XVim2#269]
Hi there,

I'm getting the following error during the compilation of the ~branch~ tag xcode11.3

```
/tmp/XVim2/XVim2/Xcode/SourceCodeEditorViewWrapper.s:57:12: error: unexpected token in argument list
    andq $0FFFFFFFFFFFFFFF0H, %rsp
           ^
Command CompileC failed with a nonzero exit code
```

OS: 10.15.2

Any idea?

**Comment by pebble8888** [comment]
I can't reproduce it.
4436b68
Xcode 11.3 beta
macOS 10.14.6

**Comment by pebble8888** [comment]
`xcode11.3` branch doesn't exist.

**Comment by JaviOverflow** [comment]
It's a tag sorry, not a branch

**Comment by pebble8888** [comment]
xcode11.3 tag also doesn’t exist too.

**Comment by JaviOverflow** [comment]
My bad -- I confused 11.3 with 10.3. We can close this sorry
