### ISSUE TITLE
Xcode 11.3 not working...

### ISSUE THREAD

**Issue by maitriyogin** [XVimProject/XVim2#276]
Hi,
I can't seem to get it working with Xcode 11.3.
I'm able to build, well at least I get a `build success` message.
Note: I've tried with both the develop and master branches, there's no tag for 11.3 so I kind of assumed that I should try the latest and greatest..

The location of Xcode is correct..
xcode-select -p
/Applications/Xcode.app/Contents/Developer

When I open Xcode I don't get any notification that xvim is installed.. I was kind of hoping for an alert or at least some sign ... of it being there.

I'm a total newbie so it might just be a setting in preferences that I've totally missed.

Huge thanks for your help and what looks like an awesome  plugin,
/Stephen.

**Comment by kien-huubap** [comment]
Hi, I just installed it on Xcode 11.3, it works.
Make sure you re-sign your Xcode by following the instruction here: https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by allenhsu** [comment]
Have you tried `defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.3` and relaunch Xcode?

**Comment by huos3203** [comment]
I try install xvim on Xcode11.3，but Xvim don't work

**Comment by Jarreddebeer** [comment]
I had the same issue as @maitriyogin, having done the re-signing. 

The first time opening XCode I was prompted for my password to 'Allow' (I think the new signing but I can't remember) but I did not get the plugin prompt nor any sign of XVim2.

I closed XCode. After ensuring the repo was clean with git checkout -- ..., I then ran 'make' a second time, and this time when opening XCode I got the plugin prompt and it worked.

**Comment by johnlim** [comment]
Hi, I'm similarly trying to install for Xcode 11.3. After following the install steps and launching Xcode, I get a `Unexpected code bundle "XVim2.xcplugin"` prompt but after clicking `Load Bundle`, vim bindings are still not enabled.
![Screenshot 2020-01-09 at 3 55 01 PM](https://user-images.githubusercontent.com/2478187/72048820-987f9e00-32f8-11ea-8c89-30680b780334.png)
Any help? Thanks.

**Comment by harryhan24** [comment]
look so strange. in my case it work perfectly on v11.3

**Comment by johnlim** [comment]
> look so strange. in my case it work perfectly on v11.3

Do you get that `"XVim2.xcplugin"` prompt?

**Comment by harryhan24** [comment]
> > look so strange. in my case it work perfectly on v11.3
> 
> Do you get that `"XVim2.xcplugin"` prompt?

Nop. i dont have.  below is my enviroment
Catalina - 10.15.2 (19C57)
Xcode - Version 11.3 (11C29) with Xvim fresh install.

**Comment by FightingEveryDay** [comment]
I`m Xcode 11.1 , not working too, It looks like the same problem = =!!

**Comment by maitriyogin** [comment]
Hiya, sorry been away for a bit.
Ok, so I got the dialog appearing now and have answered yes ...
But what next?
how do I then enable it in Xcode? should it be in preferences/key bindings?
/Stephen.

**Comment by maitriyogin** [comment]
it works! forgot to code sign...
Huge thanks!

**Comment by willbchang** [comment]
> Have you tried `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.3` and relaunch Xcode?

This resolved my issue on Xcode 11.3.

**Comment by mapte05** [comment]
I had this problem as well, and I just rebuilt XVim2 and then vim started working in xcode

cd <Xvim2>
rm -rf build
make

my environment is: macos catalina 10.15, xcode 11.3
