### ISSUE TITLE
Relativenumber not work.

### ISSUE THREAD

**Issue by ingocraft** [XVimProject/XVim2#28]
XVim2 work for me,
but when I set up my `.xvimrc` as below,
```
set relativenumber
```
the relative number not appear in my Xcode9.
Did I miss something?

**Comment by antmd** [comment]
relative number is not supported yet. Relativenumber is the last major enhancement needed for XVim2, as far as I can see, and it's not obvious how to add it, yet. I'll open this up for anyone to give it a go!

**Comment by kr15hna** [comment]
hey, what tool are you using to get class declarations for SourceEditor framework? 
I tried class-dump but its giving error (Invalid parameter not satisfying: listHeader.entsize == 3 * [self.machOFile ptrSize] + 2 * sizeof(uint32_t))

**Comment by kr15hna** [comment]
Hey, line numbers are handled by "SourceEditor.SourceEditorGutterMarginContentView" it has an array of "SourceEditor.SourceEditorFontSmoothingTextLayer" and looks like this contentView is reusing these layers.It seems tough to use these layers for relative number, Is it fine to add a new view? overlaying SourceEditorGutterMarginContentView and handle numbering on our own.

**Comment by antmd** [comment]
Hi @kr15hna. Please go ahead and do what you think is necessary.

I use class-dump for the objc bits. I can't remember if I'm using the latest from https://github.com/nygard/class-dump, or this branch: https://github.com/0xced/class-dump/tree/swift-binaries

For the other names, I run the following:

    nm -U /Applications/Xcode.app/Contents/SharedFrameworks/SourceEditor.framework/SourceEditor | swift-demangle -simplified > /tmp/demangled.txt
    nm -U /Applications/Xcode.app/Contents/SharedFrameworks/SourceEditor.framework/SourceEditor > /tmp/mangled.txt
    join <(sort -k 1 /tmp/demangled.txt) <(sort -k 1 /tmp/mangled.txt)

**Comment by dylanhand** [comment]
+1 for relative numbers

**Comment by juanj** [comment]
I posted a bounty on this.
https://www.bountysource.com/issues/50244706-relativenumber-not-work

If anyone else wants to see this being implemented can contribute to the bounty.

**Comment by mokagio** [comment]
I'm trying to look into this, but I have no idea of what I'm doing?

What's a good place to start? 

@kr15hna suggested:

> line numbers are handled by "`SourceEditor.SourceEditorGutterMarginContentView`" it has an array of "`SourceEditor.SourceEditorFontSmoothingTextLayer`" for each line and looks like this contentView is reusing these layers.It seems tough to use these layers for relative number, Is it fine to add a new view? overlaying SourceEditorGutterMarginContentView and handle numbering on our own.

How can we get a reference to that class? So far in my reverse engineering I've been able to see the subviews of `XVimIDEPegasusSourceEditorView`.

<img width="1792" alt="screen shot 2018-11-21 at 8 49 08 am" src="https://user-images.githubusercontent.com/1218433/48805201-d8896780-ed6a-11e8-8eec-e3b57bc47b41.png">

Among them I can see a `ChangeGutterMarginView`, which _I think_ matches this:

https://github.com/XVimProject/XVim2/blob/76852cf78332f53252eadb4f281f6530fbd2cb5f/XVim2/Xcode10/IDESourceEditor/_TtC15IDESourceEditorP33_7E074BCA936D0EABA73257D5271D839D22ChangeGutterMarginView.h#L9-L21

I might be wrong though. I tried to call `isFlipped` on it and it didn't work, but I don't know why:

<img width="1792" alt="screen shot 2018-11-21 at 8 50 04 am" src="https://user-images.githubusercontent.com/1218433/48805331-36b64a80-ed6b-11e8-980d-ce291c901713.png">

Any ideas if I'm on the right track?

Ideally I'd like to:

1. Somehow get a references to the gutter view
2. Find out how to modify its content
3. Write logic to derive the array of relative line numbers from the current one
4. Understand where the hook for any line movement in the source window is
5. Modify the content of the gutter after a movement

**Comment by kr15hna** [comment]
@mokagio I don't have access to mac I can't  help you much.
but from what I remember..
1. for getting reference to any view just use [ :subViews] method from window(?  or any other parent view you have) and loop until you find it.

2. the gutter view(or its child view) has some reusable layers for numbers, I don't remember but I was not able to change layers content. only way I could thought of is just hiding this line number view and just add custom view and do  everything but then it became very laggy(but my implementation was straight forward and no optimizations)

**Comment by vincentsong** [comment]
Any update on this issue? Is it possible to implement it?

**Comment by mokagio** [comment]
Unfortunately, I haven't had the time to look into this again. Sorry 😞

**Comment by kentrh** [comment]
Hi, just want to say I really enjoy XVim2 and Vim mode is an absolute must for me when using an editor. Also as mentioned earlier in this thread, I've also grown custom to the relative line numbers and it's quite shitty when they're not there. 

That being said I have tried over the last couple of days to find a way to get it working in this project, but I think I need some help from somebody with a bit more experience in both Obj-C (haven't touched it in five years I think) and the type of project XVim2 is. My experience is solely with iOS apps, so I feel I'm lacking the fundamental stuff here. 

Okay, so I have managed to scrap together a somewhat really buggy thingy, that in my opinion is better than not having any form of relative line numbering at all. It has the following bugs/features:

- Shows relative line numbering when moving around, but might have to do a key stroke to make it visible (again) if it's a first launch or some other command has been executed. I haven't figured out where to put the code so that it always will replace the normal numbering.
- It only works when `Line Wrapping` is turned off. Line wrapping screws up the math for calculating which line it is, based on the Y coordinate.
- It respects the `relativenumber` setting in `.xvimrc`
- It may break with other settings than mine given that I use the Y coordinate of the layer to calculate which line number I'm dealing with. I haven't tested this fully. 

Okay so please test if you wish, and pretty please help me solve this by submitting code or pointers. Anything is appreciated. I really wish to see relative numbers fully functioning in the XVim2 project. 

Fork/branch: https://github.com/kentrh/XVim2/tree/relative-line-numbers
Screenshot: 
<img width="839" alt="rn" src="https://user-images.githubusercontent.com/675434/99447229-72b32480-291f-11eb-9ea7-cc4c0601e06a.png">

**Comment by mokagio** [comment]
@kentrh YOU. ARE. A. LEGEND!

Thank you so much for this. I'd love to get you a drink, have you got a PayPal or somewhere similar where to send it?

I checked out your branch, run `make` and took it for a quick spin. I noticed a few things:

**Not working on first launch**. You mentioned this in your [comment](https://github.com/XVimProject/XVim2/issues/28#issuecomment-729209334) but I wanted to report that the only way I found to enable it was to run `:set relativenumber` from normal mode

**Not respecting font size**. This is a minor detail, but, as you can see below, the font size of the number is not the same as they were originally. I suppose there must be a way to read the font size and apply it to the new views your code adds.

![XVim-Demo-1](https://user-images.githubusercontent.com/1218433/99468401-9a909f80-2994-11eb-8f39-065e5ae02aa9.gif)

**Line number goes to `1` when on one-before-the-last line** 

![image](https://user-images.githubusercontent.com/1218433/99468566-f78c5580-2994-11eb-89ab-135f2e2f1cd7.png)

I'll be using it more today and report here with other findings.

This is super promising. As far as I'm concerned, unless someone spots a bug, it should make it into `develop` ASAP.

It's an optional feature, so even if it's not super polished it's okay. Also, I think it's fair to say that most of the users of XVim are tinkerer and can understand the complexity of getting this kind of stuff working.

Again, thank you so much! ❤️ You are awesom!

**Comment by kentrh** [comment]
Thank you so much @mokagio! That's really nice of you, but your appreciation is good enough for me! 

I'll dive a bit deeper into the font size thingy, I think that may be the reason for the "off by 1" line number that sometimes occurs. Tried to get the theme settings from Xcode to get the font size and use this, but haven't lucked out yet.

But doesn't your Xcode pickup the `set relativenumber` in your `.xvimrc` file in you home directory? I have to restart Xcode for it to pickup changes to `.xvimrc` though, but it works setting it there. Don't have to do it inside Xcode.

**Comment by mokagio** [comment]
> But doesn't your Xcode pickup the `set relativenumber` in your `.xvimrc` file in you home directory?

That turned out to be an issue with my `.xvimrc`. Apparently, having inline comments prevented XVim2 from parsing the setting. [This](https://github.com/mokagio/dotfiles/commit/2c8663b9ef6e5864602124a84c481e29934686ff) fixed it.

```diff
- set relativenumber " comment
+ " comment
+ set releativenumber
```

It now loads as soon as I launch Xcode 🎉 🙌

**Comment by kentrh** [comment]
@mokagio nice! 

Okay, so I managed to pull the theme config from Xcode and use font colors and sizes so from what I've tested it looks like it works most of the time. I don't think you actually can set the numbering layout in the theme section, but I think it's derived from the `Plain Text` section, so I tried to mimic that. 

I think I've tried a dozen different ways to get the line numbers and calculate Y coordinates, but I haven't found a bullet proof solution yet, but I think this is as good as it gets right now. 

There may be variations in font types, sizes and paddings that may screw up the calculations, but if this version is tested okay enough, I can create a pull request.

**Comment by mokagio** [comment]
Should this issue be closed now that @kentrh's excellent work has been merged?

**Comment by juanj** [comment]
I think so, relative numbers not being displayed is no longer an issue.

@kentrh This is amazing! Thank you very much for you work! Please feel free to claim the bounty at https://www.bountysource.com/issues/50244706-relativenumber-not-work

**Comment by davidbjames** [comment]
Can this be fixed *with* line wrapping enabled in Xcode? If someone thinks that can be done (seems reasonable?), we should create a new issue.
