### ISSUE TITLE
Not working in Xcode 11.3.1

### ISSUE THREAD

**Issue by aganm** [XVimProject/XVim2#287]
I install xvim2 from develop branch, start xcode, click load bundle.
Then I open the editor, no vim bindings. Just regular xcode.

Mac os catalina 10.15.3
Xcode 11.3.1 11C504

**Comment by sdondley** [comment]
Same.

**Comment by sdondley** [comment]
This did the trick: https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by aganm** [comment]
I tried signing but still no luck. No xvim showing up.

**Comment by aganm** [comment]
Okay, now it's working. I resigned again, removed xvim2, reinstalled xvim2, restarted xcode. Wouldn't work. I resigned, reinstalled xvim2, restarted xcode. Now it's working. Oh well.
