### ISSUE TITLE
Plugin isn't loaded for Xcode 11.3.1

### ISSUE THREAD

**Issue by alanf** [XVimProject/XVim2#289]
I've used XVim2 for the last several versions of Xcode, but since updating to Version 11.3.1 (11C505) the bundle isn't loaded even after resigning and `make`-ing XVim2. Are there any steps I can try to get XVim2 working on this new version?

**Comment by sohnryang** [comment]
Having the same issue. Is there any breaking changes between Xcode v11.2 and v11.3?

**Comment by sohnryang** [comment]
Well, it seems that XVim2 just work fine on Xcode 11.3.1.. I forgot to re-sign it.

**Comment by sohnryang** [comment]
@alanf Did you try re-signing Xcode?

**Comment by alanf** [comment]
@sohnryang for me, it was actually this that  I needed to do:

`defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.3.1`

And it loaded after that!
