### ISSUE TITLE
Code completion not working in 11.3.1

### ISSUE THREAD

**Issue by pelachile** [XVimProject/XVim2#292]
XVim2 is working fine except for a lot of the key bindings like Shift $ to go to the end of a line don't work. However, code completion is not working at all

**Comment by pebble8888** [comment]
Try to reboot macOS.

**Comment by pelachile** [comment]
Yeah, I tried that. I had to give up on it. I'm so used to Vim key binding it is almost impossible to code in Xcode now without them. I decided to use AppCode and just deal the hassle of switching back and forth.
