### ISSUE TITLE
Xcode 11.4 isn't working with XVim2

### ISSUE THREAD

**Issue by dhalonen-rl** [XVimProject/XVim2#294]
I've updated the 11.4 b1-3 w/o issues. The release version isn't working. Resigned w/ cert, did make, says all went well.

The instructions for removal:
 defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-X.X

Don't seem to work as com.apple.dt.Xcode is no longer recognized.

What say you?

**Comment by dhalonen-rl** [comment]
Fake news!
After several restarts of Xcode, XVim2 loaded! Whew.

**Comment by trietphm** [comment]
Me too, need to resign to get it works. Phew.

**Comment by Elypson** [comment]
I also had the issue that it said "domain not found". Interestingly, `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.4` did not work but `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-11.4.1` did not yield any error
