### ISSUE TITLE
After resigning, other extensions become disabled

### ISSUE THREAD

**Issue by Kyle-Ye** [XVimProject/XVim2#299]
After resigning my Xcode 11, I can use XVim2 successfully. But it seems other offical extension got disabled. And in "System Preferences -> Extensions", there is no "Xcode Source Editor" now, which is the default place to enable the Xcode Extension.

Although this question is not related to the XVim2 project, I still want to know whether it is possible to both having XVims and other offical plugins?

Thanks a lot.

**Comment by ryanmeisters** [comment]
I was frustrated by this for a while too (I neeeeeed [SwiftInitializerGenerator](https://github.com/Bouke/SwiftInitializerGenerator)! After much messing around trying to figure it out, I think that official extensions can't be **_**installed**_** in a self-signed Xcode, BUT they will still work in self-signed Xcode after being installed in official Xcode.

Here's what works for me:
1. `sudo xcode-select -s /Applications/Xcode.app # Real Xcode, not self-signed`
2. Install/run any official extensions. You should see them show up in `System Prefs > Extensions > Xcode Source Editor`. Make sure to check the checkboxes to enable them
3. If you now open your self-signed copy of Xcode, your extensions should be there

note that you do not need to `xcode-select` back to your self-signed copy of Xcode

**Comment by Kyle-Ye** [comment]
I got it, thank you very much.
