### ISSUE TITLE
Movement Commands Incorrect on Second Launch

### ISSUE THREAD

**Issue by grantjk** [XVimProject/XVim2#30]
On first launch of Xcode after installation, everything works great! (Thanks!)

However, as soon as I quit Xcode and relaunch it, the `k` key moves the cursor down 1 line, and the `j` key moves the cursor down multiple lines.  I can reproduce this reliably on my machine.

To fix, I have to uninstall the plugin, launch Xcode, quit Xcode, reinstall the plugin, and then launch Xcode again.

I'm happy to provide more debugging information if you let me know what you need.

**Comment by antmd** [comment]
This sounds similar to another issue: #4 Please check you do not have another version of XVim installed.

**Comment by grantjk** [comment]
You're right! Sorry I missed that.
