### ISSUE TITLE
i[ and i{ not working

### ISSUE THREAD

**Issue by seblj** [XVimProject/XVim2#300]
When trying to delete,  yank etc... inside "[" or "{" with for example "di{" it does not work. Nothing happens.
This does however work with di" and di( for example

**Comment by genkobar** [comment]
Is this still not working for you? Which versions of Xcode, macOS and XVIM2 are you on?

The commands "di[", "di]", "di{", "di}", "yi[", "yi]", "yi{", "yi}" all work fine for me. 
I'm on macOS 10.15.6, Xcode 11.5 (11E608c) and using XVim on the master branch at commit `6356710fdf4a7edc816d49474ad6c415afc70897` (from July 12).

**Comment by seblj** [comment]
No it still does not work... I am currently on macOS 10.15.5, Xcode 11.6 and using XVim2 on the master branch at the same commit as you
