### ISSUE TITLE
class-dump doesn't work for frameworks in Xcode12

### ISSUE THREAD

**Issue by pebble8888** [XVimProject/XVim2#305]
https://github.com/pebble8888/class-dump

cd XcodeHeader/SourceEditor
class-dump -H /Applications/Xcode.app/Contents/SharedFrameworks/SourceEditor.framework/SourceEditor

**Comment by pebble8888** [comment]
The `classdump` doesn't support RW_REALZING and RW_METHOD_ARRAY flags.

**Comment by pebble8888** [comment]
It may be relate with Objective-C runtime optimization.
 
https://developer.apple.com/videos/play/wwdc2020/10163/

**Comment by petergp** [comment]
Its still possible to create the headers using Hopper Disassembler. Let me know if you need a dump

**Comment by pebble8888** [comment]
@petergp 

Thank you for the information.
I will try Demo version.

**Comment by pebble8888** [comment]
The branch looks like working for Xcode12.
https://github.com/hosijyun/class-dump
