### ISSUE TITLE
Xcode 12 - Yank/Put for clipboard is broken

### ISSUE THREAD

**Issue by rudedogg** [XVimProject/XVim2#306]
It seems like yanking isn't working correctly. When trying to yank a line with `yy` and paste it with `p` I get no output. Same with other yank commands, ie: `yw`, etc.

I think it may just be yank that is broken, so paste doesn't output anything.

Also, thank you for all your work on this pebble8888!

**Comment by superarts** [comment]
Same problem here with Xcode 11.5. Yank seems to be doing nothing at all. Put should be fine as it still pastes a blank line.

**Comment by pebble8888** [comment]
Please read here.
https://github.com/XVimProject/XVim2#bug-reports

**Comment by chml** [comment]
PR for this.
#308
