### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by ryleyherrington** [XVimProject/XVim2#31]
So I've tried everything I can think of to make this work. I'm sure I'm doing something dumb but it seems like everyone else has it working in Xcode 9 just fine. 

Steps I've taken: 

- Made sure every install of xcode (previous) has been removed.
- Clean install of xcode 9.0 (9A235). Resign with a brand new certificate just like the steps said (I've used xvim for years and never had an issue with this part at least).
- Validate xcode-select -p is pointing to my Xcode which is default placement. Nothing crazy here.
- Clone XVim2, used `master` 
- Set the team for signing in the XVim2 Project (This could be wrong.... maybe I should leave it blank)
- `make` and I get

```XVim2 $ make
xcodebuild -configuration Release 
2017-10-13 10:57:48.246 xcodebuild[67775:4729937] WARNING: Failed to load plugin at path: "/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signature in (/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2, NSDebugDescription=dlopen_preflight(/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signature in (/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?), NSBundlePath=/Users/___COMPYNAME___/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin, NSLocalizedDescription=The bundle “XVim2” couldn’t be loaded because it is damaged or missing necessary resources.}
=== BUILD TARGET XVim2 OF PROJECT XVim2 WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **
```
But when I open Xcode it asks me to Load the bundle and I click "yes" and then nothing happens. Xcode won't open there. It doesn't crash though; it just doesn't open. Obviously thats because it can't find the bundle but idk what to do to fix it. 

When I open it again(ie double click an .xcodeproj) it opens just fine but XVim isn't up and running.

Any help appreciated. I also added another uuid to the Info.plist because that was my initial error.

**Comment by ryleyherrington** [comment]
Finally figured it out. But I can't mark it as resolved. Cached value of xvim2 from an old branch wasn't being replaced. 

So... we can close this issue.

**Comment by AShandrakov** [comment]
Try to prepare code sign certificate. 
https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md 
step 2
It helps me with the same problem.

**Comment by ryleyherrington** [comment]
Again, already figured out the issue. Just can't close the ticket. Thanks for responding though!

**Comment by antmd** [comment]
Thanks for letting me know.
