### ISSUE TITLE
Can't see input bar in Xcode 12 Beta

### ISSUE THREAD

**Issue by FredrikAugust** [XVimProject/XVim2#310]
When I press `:`, I can't see the input bar. Something does take focus however, but things like `:q` do nothing.

- Xcode Version 12.0 beta (12A6159)
- Built from 6e32166eacd9c5cbda9501ac781ab69de7dffa99

**Comment by FredrikAugust** [comment]
When splitting windows, `:q` does close the window, but I can't see what I type.

It does not, however, close tabs.

**Comment by ctlacko** [comment]
Seems like a TODO: https://github.com/XVimProject/XVim2/commit/1b69484326b280b305f82f18516d0a3612654e9b

**Comment by xiangyu0801** [comment]
# @

- [ ] 

1.

**Comment by aruffolo** [comment]
still not working on Xcode 12 now that is not beta anymore
