### ISSUE TITLE
Xcode 12 Beta Preview crashes when using navigation stack (C-I & C-O)

### ISSUE THREAD

**Issue by FredrikAugust** [XVimProject/XVim2#311]
When pressing C-I or C-O Xcode crashes.

- XVim2 commit: 6e32166

Crash report:
[crash-report.txt](https://github.com/XVimProject/XVim2/files/4936374/crash-report.txt)

**Comment by pebble8888** [comment]
The crash is fixed for global mark jump.
Global mark jump feature is removed.
