### ISSUE TITLE
Ctrl-E isn't working

### ISSUE THREAD

**Issue by fedorpashin** [XVimProject/XVim2#315]
I'm on develop branch and using Xcode 12 beta. Ctrl-Y is working, but Ctrl-E is not.

**Comment by cb-bffmike** [comment]
Verified this is still broken on Xcode Version 12.0.1 (12A7300).

**Comment by r-plus** [comment]
hmm, confirmed on Xcode 12.2
Ctrl-Y also broken.

**Comment by pebble8888** [comment]
Fixed.
