### ISSUE TITLE
Working for Xcode 12 beta 6? 

### ISSUE THREAD

**Issue by davidbjames** [XVimProject/XVim2#319]
Xcode 12 beta 4 was working fine, but upgrading to beta 6 it no longer works.

I'm on develop branch and tried clearing the defaults like so:
``` defaults delete  com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-12.0```

.. and restarting Xcode. It asked if I want to load the bundle, which I did, but XVim2 is not loaded.

Is there anything else I should try?

**Comment by miotke** [comment]
Adding to this as well. I'm running Xcode 12 beta 6 and can't seem to get XVim2 to work. 

### Steps to reproduce
* Followed the install instructions in the README
    * Received `** BUILD SUCCEEDED ** [20.769 sec]` after running `make`.
    * Launched Xcode 12 beta 6  and selected "Load Bundle" when asked.
    * XVim2 does not load or is not working when editing files.
* Ran `defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-12.0` and selected "Load Bundle" again with the same results, XVim2 did not load or is not working when editing files.

Either we are missing a step or did beta 6 change something for extensions?

**Comment by qiudaomao** [comment]
why everyone forgot to resign Xcode.. It's in the readme already #613

**Comment by miotke** [comment]
@qiudaomao is totally correct and this is my bad(thanks for pointing this out). Resigning Xcode is the solution and is #1 in the README. 🤦‍♂️

@davidbjames for visibility. 

Docs are here for instructions on how to resign Xcode https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md

**Comment by davidbjames** [comment]
Yes, this was the problem. I signed the wrong Xcode (not the beta one)!
