### ISSUE TITLE
Is there a dotfiles-automable way to install XVim?

### ISSUE THREAD

**Issue by danielfalbo** [XVimProject/XVim2#320]
I currently use [dotbot](https://github.com/anishathalye/dotbot) to bootstrap my dotfiles and the XVim installation is one of the few things I still do manually

**Comment by tami5** [comment]
> Thank you! Yeah, looks like `security add-certificate /path/to/certificate` is the command line equivalent way. Unfortunately I know nothing about security and how to create the certificate in first place, after a quick look on the internet looks like the certificate could be created in the terminal via `openssl`. Anyway I'm not going to dive deeper for now, maybe I'll invest more time in this later.

Did you figure it out, are you still using the extension :)

**Comment by danielfalbo** [comment]
> Did you figure it out, are you still using the extension :)

I'm still using the extension but I still install it manually every time I reinstall macOS 😅

**Comment by r-plus** [comment]
I recently add script for CI.
https://github.com/XVimProject/XVim2/blob/master/Tools/create_cert.sh

**Comment by danielfalbo** [comment]
Just reinstalled macOS and tested the script, works like a charm, thank you 😄!
