### ISSUE TITLE
Xcode 12.1 (12A7403) not valid~

### ISSUE THREAD

**Issue by ysnows** [XVimProject/XVim2#332]
Version 12.1 (12A7403)

**Comment by xincc** [comment]
want to create the same issue

**Comment by ysnows** [comment]
finally,
in my case, i exec `cp -rf /Users/ysnows/XVim2/build/Release/XVim2.xcplugin ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/` after `sudo make`
