### ISSUE TITLE
Readme.md should be updated in various ways

### ISSUE THREAD

**Issue by e-sung** [XVimProject/XVim2#34]
I found this project was so helpful, that I tried to make Korean version of Readme.md file of it.
And while doing so, I found some outdated flaws.
And I decided that I should make translation _after_ those errors are fixed

## 1. Branch and Relaease section
It says you have "master" branch and "develop" branch.
XVim project does have "develop" branch, but XVim2 doesn't. 
It really confused me, because it says " Any pull requests should be made to 'develop' branch"
This needs to be clarified.

## 2. Contributing.md link is broken
I'm not sure whether Contributing guideline of XVim2 project is same as that of XVim Project.
If it is, link should be directed to Contributing.md file of XVim project.
If not, you should upload Contributing.md and fix the link. 

## 3. Japanese translation of Readme.md link is broken
It seems XVIM2 project doesn't have README_jp.md file. 
Also, README_jp.md file of XVim project is way outdated. 
This link should be updated or removed. 

This is really awesome project and I can't tell you how much I am benefited from it.
Thank you so much for this wonderful project.

**Comment by pebble8888** [comment]
Fixed in develop branch.

readme.md translation file cn and jp is removed.
A translation file is too hard to maintain.
So we don't need that.
