### ISSUE TITLE
the relative line number is not correct

### ISSUE THREAD

**Issue by ysnows** [XVimProject/XVim2#344]
MacOs Catalina Version 10.15.7 (19H15)
Xcode Version 12.1 (12A7403)

![image](https://user-images.githubusercontent.com/11255869/100402955-7faae300-3098-11eb-9560-a8c63779dabb.png)

**Comment by davidbjames** [comment]
**This occurs whenever there are lines lengths that exceed the current editor width which throw off the relative line number by as many lines as are wrapped.** This occurs when the cursor is below the line wraps. For example, if you have a long line of code that will not fit within the editor window (i.e. it wraps) the relative line number will be off by the number of wrapped lines. On the other hand, if you make the editor window larger so the line no longer wraps then relative numbers will work again.

**Comment by kentrh** [comment]
Yeah, I stated this in the original issue (https://github.com/XVimProject/XVim2/issues/28#issuecomment-729209334), so for now you just have to turn off line wrapping in xcode settings for it work.

**Comment by ysnows** [comment]
`turn off line wrapping in xcode settings` works, thank you...
