### ISSUE TITLE
wired jump when enables Xcode trim trailing whitespace settings and whitespace-only lines

### ISSUE THREAD

**Issue by ooopscc** [XVimProject/XVim2#351]
![2021-01-12 01 08 55](https://user-images.githubusercontent.com/1056803/104215668-0e6e9600-5474-11eb-95c3-46dc92da02e6.gif)

**Comment by r-plus** [comment]
NOTE:
`{<CR><Esc>j` will happen this issue.
`{<CR><Esc>k` will not happen.
