### ISSUE TITLE
Xcode 12.3 Rosetta Mode Apple ID issue

### ISSUE THREAD

**Issue by johnwylie70** [XVimProject/XVim2#355]
Switching Xcode seems to be a temporary fix for getting XVim2 bindings working.

I had just updated BigSur to latest version, in the process it asks you for your iCloud/Apple ID credentials again which I did

At this point I installed XVim2 for my first time to try it. Re-signed Xcode etc, I noticed that I needed to re-login to my apple developer account via Xcode preferences, but it keeps saying "Couldn’t communicate with a helper application."

I assume because I have re-signed Xcode?. I guess I can delete Xcode and restart the process of installing Xcode, setting up my developer accounts and then installing XVim2?

Is there an easier way or a workaround for this one?

either way I thought I would let you know about this situation.

**Comment by ch3n0l1** [comment]
Yep, i got the same problem. I have to reinstall a new xcode when i need to switch/sign in any developer accounts.

**Comment by chaozbj** [comment]
same problem on M1 mac, I need to delete xcode and reinstall it without XVim2. Hope there is solution for that. No XVim is terrible ~~~~

**Comment by cstlex** [comment]
Same for me and I just installed 2 Xcodes one with xvim and one without xvim.

**Comment by pebble8888** [comment]
duplicate #340
