### ISSUE TITLE
Can't Use <C-a> and <C-x> and there is a view bug with using <C-v>

### ISSUE THREAD

**Issue by BBHNation** [XVimProject/XVim2#36]
XVim2 maybe too new, I installed it on my Xcode 9.0, and I Can't use <C-a> & <C-x>, THE IMPORTANT: I Can't use <C-v> to edit Muti-Rows.

**Comment by antmd** [comment]
Please pull 'master', make clean, then make. Let me know if it now works or not.

**Comment by BBHNation** [comment]
You have done a great job! @antmd ,yes the latest 'master' have fix this issue. I can use <C-a> <C-v> with happiness.
