### ISSUE TITLE
shift o deleting characters under cursor

### ISSUE THREAD

**Issue by mickeysox** [XVimProject/XVim2#363]
When inserting a new line above the current line, the character under the cursor is deleted.

Initial text
<img width="702" alt="Screenshot 2021-02-22 at 22 52 50" src="https://user-images.githubusercontent.com/5666707/108780716-bb066200-7560-11eb-9626-247222ca6d5d.png">

shift + o
<img width="702" alt="Screenshot 2021-02-22 at 22 52 56" src="https://user-images.githubusercontent.com/5666707/108780711-b9d53500-7560-11eb-975f-2481cde351f2.png">

character under cursor is deleted.

This is a vanilla installation of XVim2, the only option I have set in my .xvimrc is ```set relativenumber```

Could someone please check if this can be replicated, or if it is local to my installation.

Thanks.

**Comment by pebble8888** [comment]
#144
