### ISSUE TITLE
`C-e` stops working when a second "window tab" is opened

### ISSUE THREAD

**Issue by sashaweiss** [XVimProject/XVim2#365]
Hi! Thanks in advance for your help here.

I'm on Xcode 12.4, 2019 MBP 16" (Intel). When I start up Xcode the `C-e` movement will work fine, until I open a second "window tab" (Cmd+T). At that point, editors in the new tab can use `C-e` just fine, but editors in the first tab stop being able to move with `C-e`. Specifically, if I have a half-visible line at the bottom then pressing `C-e` will move the editor such that the half-visible line becomes fully visible (bottom of the line aligned with bottom of the editor), but won't move further down. The issue persists even if I close the second tab, although if I open a "new second tab" the editors in that tab work fine. Closing the Xcode window and re-opening it fixes the issue.

`C-y` works fine in all the editors, even after `C-e` breaks. `C-d` and `C-u` also still work.

Any idea what's going on? Happy to help debug further if you can point me in the right direction.

**Comment by r-plus** [comment]
@sashaweiss I fixed this issue, try current develop branch version. thx.

**Comment by sashaweiss** [comment]
Amazing thank you!
