### ISSUE TITLE
Xcode 12 / Big Sur Status

### ISSUE THREAD

**Issue by yourhead** [XVimProject/XVim2#368]
There does not seem to be a branch targeting Xcode 12.

I have tried using master on Xcode 12. It builds and installs without error. But when I dig through the console it seems to be having codesigning issues.

```
WARNING: Failed to load plugin at path: "/Users/iac/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/iac/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2): no suitable image found.  Did find:
	/Users/iac/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: code signature in (/Users/iac/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	/Users/iac/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim2.xcplugin/Contents/MacOS/XVim2: stat() failed with errno=1" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/iac/Library/Application Support/Developer/Shared/Xc
```

Would a pre-built and codesigned release solve this issue?

**Comment by r-plus** [comment]
are you using codesigned xcode.app?

**Comment by yourhead** [comment]
all i know about that are some comments here and there. are there instructions for doing that?

also: is that the "official" solution? is there no way to do things in a more correct way?

and…   is there somewhere that explains all this? i was just going by the readme -- which, if i'm not mistaken doesn't say anything about this in the installation section.

**Comment by r-plus** [comment]
that is described on initial instruction of install https://github.com/XVimProject/XVim2#install

**Comment by yourhead** [comment]
fair enough. i guess that counts me out. thanks.
