### ISSUE TITLE
Does this support on XCode 12.4?

### ISSUE THREAD

**Issue by martinsotirov** [XVimProject/XVim2#370]
I loaded the bundle when I started XCode for the first time after building XVim2 but then there is no vim mode in XCode.

**Comment by r-plus** [comment]
supported 12.4. 

You must re-build XVim2 when you switch to newly version of xcode because UUID of xcode must place to info.plist to load plugin.

**Comment by martinsotirov** [comment]
@r-plus I did so and then loaded the bundle upon starting Xcode but I don't have NORMAL mode and Vim shortcuts. Do I need to enable it somehow in the IDE after it's loaded?

**Comment by martinsotirov** [comment]
Nevermind. I followed the self signing instructions from the guide for Xcode 8 and it worked for 12.4. https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md
