### ISSUE TITLE
Xcode 13 - Vim Supported. Thank you Xvim!

### ISSUE THREAD

**Issue by escakot** [XVimProject/XVim2#380]
Xcode 13 will have Vim Mode now. 🎉 🎉 
I just want to say thank you so much for XVim maintainers esp. @pebble8888.

Source: https://developer.apple.com/xcode/

![image](https://user-images.githubusercontent.com/4576455/121080855-fa705b80-c7a9-11eb-996b-f1eacd1c0349.png)

**Comment by JugglerShu** [comment]
The time has come. I’m glad that Xcode finally supports vim mode natively. It has been almost 10years since I first wrote code for XVim.
I haven’t worked on XVim project recent years but I’m happy to hear this.
I don’t know how much of vim features are supported in Xcode 13 but I think it will replace XVim anyway.
If any features are missing XVim can be a plug-in to complement it.
Thank you for everyone who supports XVim.

**Comment by hyouuu** [comment]
Thank you @JugglerShu! Can't express how much Xvim helped my development. Hope your health is getting better and stay well!
And many thanks to @pebble8888 to keep XVim updated in recent years!

**Comment by sebbo176** [comment]
Thank you so much for XVim ❤️

**Comment by r-plus** [comment]
I just tried Xcode 13b1 with Vim key bindings that is great for basic vim keybindings!
As @qiudaomao says, still missing many feature such as recording, visual line mode, visual block mode (can be use multiline editing feature without vim keybinding instead) and window manipulation (e.g. C-w + h/j/k/l) that I heavily using feature in my daily coding.

But this is huge step for Vim lovers. Thanks Apple, Thanks XVim!
Probably I'll continue to use and support XVim especially for window manipulation feature that very important for me.

**Comment by horizonless** [comment]
Really appreciate the effort for developing XVim! helps me a lot

**Comment by rudedogg** [comment]
> I just tried Xcode 13b1 with Vim key bindings that is great for basic vim keybindings!
> As @qiudaomao says, still missing many feature such as recording, visual line mode, visual block mode (can be use multiline editing feature without vim keybinding instead) and window manipulation (e.g. C-w + h/j/k/l) that I heavily using feature in my daily coding.
> 
> But this is huge step for Vim lovers. Thanks Apple, Thanks XVim!
> Probably I'll continue to use and support XVim especially for window manipulation feature that very important for me.

Another missing feature with the built-in Xcode keybindings is using `r` to replace the character under the cursor, or current selection in normal mode.

**Comment by t-var-s** [comment]
> If any features are missing XVim can be a plug-in to complement it.

These are great news. Thank you for all the work.

**Comment by jaimejazarenoiii** [comment]
Thank you so much XVim ❤️

**Comment by timothycosta** [comment]
This is wonderful news! Thanks to all who have contributed to XVim.

Just a reminder, if you see missing vim features in Xcode, do file feedback for them. They've mentioned this several times in the WWDC lounges. They were also quite responsive when I asked for documentation. Hopefully we'll see more features as the beta continues.

**Comment by wdcew** [comment]
Thank you for xvim developers

**Comment by reawakening** [comment]
@timothycosta That is great news. Could you point me in the direction of where we could file feedback for missing features? and is it possible to see which feedback people have have submitted already?

**Comment by timothycosta** [comment]
@reawakening https://developer.apple.com/bug-reporting/

**Comment by tspike** [comment]
OK so super duper thank you to the XVim2 developers, and we should definitely file requests for missing features to the Xcode team, but I don't think XVim2 is obsolete by a long shot yet. Huge productivity drop for me using the Xcode key bindings without recording macros, replacing characters with `r`, `:%s`, `:wq`, repeating an action with `.`, etc etc. Please keep XVim chugging along until if/when the Xcode version is usable!

**Comment by hanawat** [comment]
Thank you so much XVim developers 💖

**Comment by gonefish** [comment]
I love this project.

**Comment by xissy** [comment]
Many thanks for your tremendous works on XVim2. I’ve always enjoyed coding with it. :)

**Comment by fredfx** [comment]
Thank you Xvim !

**Comment by rudedogg** [comment]
Just gave Xcode 13.0 beta 2 a whirl and I don't see any changes to their Vim Keybindings. The following are still missing:

- Visual line mode (`shift` + `v`)
- `r` to replace the cursor with the next keypress
- `.` to repeat commands
- `=` to format code

So I think I'll be using Xvim for at least another year. I've submitted feedback about the first two issues at least.

**Comment by timothycosta** [comment]
@rudedogg Please report all of them. The more reports they get on the same issue the more likely it is they're fixed.

It might be good to create a list of issues that XVim users can just paste into apple feedback. A sort of vim open radar.

**Comment by michaeleisel** [comment]
@timothycosta what if we made another github issue for that? People could put down unique suggestions, and copy-paste from there to radars and put thumbs up emojis on suggestions to show support

**Comment by timothycosta** [comment]
@michaeleisel Yes, that's exactly what I was thinking. 

I could see either:
1. An issue here in this repo
2. A separate repo just for vim mode radars

Advantage of #1 is that Xvim2 is already well known and people would find it. The disadvantage is that actual submissions might get drowned out in discussion if it's a single thread. Maybe single issues with a specific tag?

Or, if #2, maybe we could keep it under, e.g. `https://github.com/XVimProject/XcodeBugs` so it's still associated with XVim?

**Comment by JugglerShu** [comment]
I created https://github.com/XVimProject/XcodeIssues . Use this to keep track issues of Xcode's Vim bindings.
Maybe I'll add some template to issues page.

**Comment by YJRookie** [comment]
It annoy me a lot since XVim having the issue about account sign in, now the vim mode is comming. Thanks you a lot @JugglerShu for XVim

**Comment by azinman** [comment]
Will XVim take advantage and improve the existing implementation now in Xcode 13?

**Comment by xincc** [comment]
Thanks

**Comment by nuynait** [comment]
This is the must-have plugin for me to use code for years and years. Without this plugin I cannot imaging how my hard my life is for doing my iOS development. I really appreciate this. Thank you to everyone that contributes to the XVIM!

**Comment by jairsinho** [comment]
Thank you so much to everyone involved in this project! ❤️

**Comment by chungkil** [comment]
it has many missing function for vim..

**Comment by jarrodmoldrich** [comment]
The Xcode native Vim binding in Xcode 13 is a joke.  No macros, not even `.` to repeat commands.  So glad XVim2 still kind of works on Xcode 13.

**Comment by superarts** [comment]
> The Xcode native Vim binding in Xcode 13 is a joke. No macros, not even `.` to repeat commands. So glad XVim2 still kind of works on Xcode 13.

Am I missing something here? With Xcode 14.0.1 and XVim2, I still can't use `.` to repeat commands, which is very annoying because it shuts down my mind while doing my work. :'(

**Comment by jarrodmoldrich** [comment]
@superarts  XVim doesn't work with Xcode 14 on M1.  If you're willing to use MacForge, it half-works on Intel Macs.

https://github.com/XVimProject/XVim2/issues/398

Check your menu to see if the XVim option is there.

It looks like adding very basic Vim emulation (via Editor > Vim Mode) to Xcode was a prelude for the Xcode team to drop support entirely for plugins?  I can't find any announcement about this, but the unofficial installation method that requires self-signing Xcode foretold that one day it was going to break.  

RIP XVim.  Thanks to @r-plus , @pebble8888 , and @JugglerShu for keeping the dream alive ❤️

**Comment by mickael-menu** [comment]
The dream lives on!

After mourning the death of AppCode and XVim, I started working on a very different approach: **a macOS app integrating Neovim in Xcode**. The first version is promising and I'm already using it for my daily work.

Come check it out: https://github.com/mickael-menu/ShadowVim

<img width="800" src="https://user-images.githubusercontent.com/58686775/219877113-367a0880-de31-46e3-b6a7-bf305077ec8c.gif"/>

**Comment by tspike** [comment]
@mickael-menu  amazing! Will be watching this with great interest. Thank you!
