### ISSUE TITLE
The status bar on the xcode 13 does not display

### ISSUE THREAD

**Issue by TMTBO** [XVimProject/XVim2#381]
The status bar does not display  on the xcode 13, And the cursor can't show as insert modle

**Comment by YANOUSHek** [comment]
How is the experience with XVim2 on Xcode 13. I tried the "built-in" Vim mode and it just sucks. There's no config for it. I have some very specific remaps in my vim configs everywhere and changing my muscle memory just for Xcode isn't fun.

Is XVim2 stable enough in Xcode 13 that it's possible to use it?

**Comment by TMTBO** [comment]
> How is the experience with XVim2 on Xcode 13. I tried the "built-in" Vim mode and it just sucks. There's no config for it. I have some very specific remaps in my vim configs everywhere and changing my muscle memory just for Xcode isn't fun.
> 
> Is XVim2 stable enough in Xcode 13 that it's possible to use it?

Everything works well. But the status bar does not display.

**Comment by r-plus** [comment]
fixed on develop branch.
