### ISSUE TITLE
Small Tabs Switching

### ISSUE THREAD

**Issue by hamza72x** [XVimProject/XVim2#385]
Hey!

Jazakallahu Khairan for the project.

How to switch between `GREEN` colored tabs? 
**Not** the `RED` color one.

`tabNext` and `tabprevious` moves tab of RED area.

Currently using `master` branch. Big Sur, Xcode 12.

![image](https://user-images.githubusercontent.com/48919542/133200222-91d0e9cc-32de-4929-a22c-fac3ff34121c.png)

**Comment by r-plus** [comment]
Probably XVim not support it for now.

`Cmd + Shift + ] or [` key shortcuts for that purpose are supported widely on macOS.

NOTE: I tried `:map gt <M-S-]>` key mapping but not work.

**Comment by hamza72x** [comment]
> Probably XVim not support it for now.
> 
> `Cmd + Shift + ] or [` key shortcuts for that purpose are supported widely on macOS.
> 
> NOTE: I tried `:map gt <M-S-]>` key mapping but not work.

Hmmm.

**Comment by TMTBO** [comment]
```
nnoremap sn :xcmenucmd Show Next Tab<CR>
nnoremap sp :xcmenucmd Show Previous Tab<CR>
```
Maybe this is what you need.
