### ISSUE TITLE
XVim2 not enabled in XCode after following README instructions

### ISSUE THREAD

**Issue by cloutiertyler** [XVimProject/XVim2#39]
I followed all of the steps in the README and had no errors during the process. However when I open XCode XVim2 is not enabled and there is no XVim2 in the menu. Is there something I could be missing?

**Comment by nayzak** [comment]
XCode still needs to be unsigned to plugins can work. Follow this guide https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md to do that. Or you can use this tool https://github.com/inket/update_xcode_plugins.

**Comment by cloutiertyler** [comment]
Ah, I see! Thanks so much I'll try that and report back.

**Comment by tungel** [comment]
I can confirm that XVim2 is working after running below command on my machine:

```
sudo codesign -f -s MyXcodeSigner /Applications/Xcode.app
```

**Comment by cloutiertyler** [comment]
Sorry, yep the instructions provided fixed my issue as well.
