### ISSUE TITLE
Motion keys do not work as intended

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim2#4]
Using XVim2, motion keys `hjkl` do not work as intended. Originally reported [here](https://github.com/XVimProject/XVim/issues/1074).

> Movement is really weird for me. `h` and `l` work as expected, but `j` jumps down 3 lines, and `k` goes down instead of up.
> 
> Heres a gif: http://gph.is/2y5DiQd

## Environment

- Tested on current `master` branch ( 5e6b305de3764652c187580c754369036bfb4bb1 ).
- Xcode 9 (9A235)
- macOS 10.13 High Sierra
- With and without an `.xvimrc` file
- Keys work as normal using previous Xcode 8 and Xvim 1.

**Comment by squarefrog** [comment]
This was due to the older XVim plugin still being installed:

https://github.com/XVimProject/XVim2/issues/5#issuecomment-335475168

**Comment by yukitoto** [comment]
How you delete older XVim plugin?
