### ISSUE TITLE
Inserting in visual block mode issue.

### ISSUE THREAD

**Issue by nayzak** [XVimProject/XVim2#42]
Select block of size 1x2, press `I`, input some text and press `Esc` — works as expected. Repeat this actions but selecting block of size 1x3 and longer fails as shown on gif below.

![ezgif-1-9bf70ccbea](https://user-images.githubusercontent.com/570008/31719137-66ce58e6-b44d-11e7-8d3b-c7cab8742ebc.gif)

**Comment by antmd** [comment]
Please try again with the latest version on `master`.

**Comment by nayzak** [comment]
Seems to be fixed. Thanks!
