### ISSUE TITLE
press "3>>" only indent the first line.

### ISSUE THREAD

**Issue by immane** [XVimProject/XVim2#48]
when I press `n` `>>` (n>1) , it only indent the first line.

**Comment by MavEtJu** [comment]
Working fine on 628679ace6c4705f5783313121b7401c949938f8
Fri Oct 20 14:42:07 2017 +0100

**Comment by MavEtJu** [comment]
Doesn't work fine on 04137b41ea6d7bcb4e915b06f4ed1a509f78caa9 anymore.

```
    if ([annotation isKindOfClass:[GCMGLPointAnnotation class]] == YES) {
GCMGLPointAnnotation *pa = (GCMGLPointAnnotation *)annotation;
self.wpSelected = pa.waypoint;
[self.mapvc showWaypointInfo:pa.waypoint];
    }
```

3>> on 2nd line does make it:

```
    if ([annotation isKindOfClass:[GCMGLPointAnnotation class]] == YES) {
        GCMGLPointAnnotation *pa = (GCMGLPointAnnotation *)annotation;
    self.wpSelected = pa.waypoint;
    [self.mapvc showWaypointInfo:pa.waypoint];
    }
```

Undo changes it into:
```
    if ([annotation isKindOfClass:[GCMGLPointAnnotation class]] == YES) {
        GCMGLPointAnnotation *pa = (GCMGLPointAnnotation *)annotation;
    self.wpSelected = pa.waypoint;
[self.mapvc showWaypointInfo:pa.waypoint];
    }
```

One more undo changes it into:
```
    if ([annotation isKindOfClass:[GCMGLPointAnnotation class]] == YES) {
        GCMGLPointAnnotation *pa = (GCMGLPointAnnotation *)annotation;
self.wpSelected = pa.waypoint;
[self.mapvc showWaypointInfo:pa.waypoint];
    }
```

And one more undo changes it in:
```
    if ([annotation isKindOfClass:[GCMGLPointAnnotation class]] == YES) {
    GCMGLPointAnnotation *pa = (GCMGLPointAnnotation *)annotation;
self.wpSelected = pa.waypoint;
[self.mapvc showWaypointInfo:pa.waypoint];
    }
```

And the final undo changes it back into:
```
    if ([annotation isKindOfClass:[GCMGLPointAnnotation class]] == YES) {
GCMGLPointAnnotation *pa = (GCMGLPointAnnotation *)annotation;
self.wpSelected = pa.waypoint;
[self.mapvc showWaypointInfo:pa.waypoint];
    }
```

**Comment by daviskoh** [comment]
When I try to indent using `>>` it indents 6 spaces instead of the 2 I have set. Could this be related?

**Comment by r-plus** [comment]
In my environment(4space indent preference on Xcode), `>>` and `<<` indents 8 spaces.

using c1bfeabba4f9acd842e669f0eeaa377ecba5442d version.

**Comment by immane** [comment]
I am using [`c1bfea`](https://github.com/XVimProject/XVim2/commit/c1bfeabba4f9acd842e669f0eeaa377ecba5442d) too, when I tap `n` `>>` the first line indents 8 spaces, but the other lines indents 4 spaces normally.

**Comment by antmd** [comment]
Please try the latest version on `develop` branch.

**Comment by r-plus** [comment]
@antmd In d4d9b2b02b6af6fc31edac71eea736c3a1e539ff, Looks like fixed this issue. Very thanks for your work :+1:

Env.
- macOS 10.12.6
- Xcode 9.0.1

**Comment by MavEtJu** [comment]
Works great now, thank you!

Edwin

**Comment by antmd** [comment]
Great. Thanks for letting me know.
