### ISSUE TITLE
A Bug when using ctrl-v

### ISSUE THREAD

**Issue by BBHNation** [XVimProject/XVim2#49]
![qq20171020-161520-hd](https://user-images.githubusercontent.com/9971257/31811695-0f36f43c-b5b3-11e7-9fec-e57877f06c55.gif)

There is a view bug when I using Ctrl-v, I think the edit index maybe wrong.

**Comment by antmd** [comment]
Please try again with the latest version on `master`.

**Comment by antmd** [comment]
This should be fixed on master. Let me know if not.
