### ISSUE TITLE
Linewise change / delete removes the following line

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim2#5]
### Intended behaviour

When using the linewise change key `C` (shift+c), XVim should delete from the cursor character to the end of the line. 

### Observed behaviour

Deletes to the end of the line, and the line below. 

### Screencast

![dd-image](https://user-images.githubusercontent.com/343450/31386223-f08cfefc-adbd-11e7-9ea5-d319f54d3613.gif)

## Environment

- Tested on current `master` branch ( 5e6b305de3764652c187580c754369036bfb4bb1 ).
- Xcode 9 (9A235)
- macOS 10.13 High Sierra
- With and without an `.xvimrc` file
- Keys work as normal using previous Xcode 8 and Xvim 1.

**Comment by antmd** [comment]
@squarefrog Thanks for the great screencasts! I don't see this behaviour with my tests. Any chance you could upload / push to GitHub your TestXVim project?

**Comment by squarefrog** [comment]
Probably worth me updating the readme with how to make screencasts.. but anyway.

The TestXVim project was just a new blank project created in Xcode 9. I just didn't want to poke under the hood with a current project!

I'm not entirely sure if the Xcode 9 install I have is GM or App Store, but at this point I don't think it matters too much. Are you on High Sierra?

**Comment by antmd** [comment]
I have tested on GM 9.0 (9A235) and the previous beta...not sure what build. If there were big changes, I'd expect the UUID to change, and then XVim wouldn't load. I'll try creating a new project.

The issue looks as if it's related to line endings: XVim2's skipping past the ends of lines sometimes.

**Comment by squarefrog** [comment]
Hang on.. I think I figured it out. I still had the original XVim plugin installed. And it seemed as though it was interfering. Deleting both plugins, cleaning then rebuilding has fixed it. Sorry for the false positive!

**Comment by antmd** [comment]
Thanks for letting me know.

You mention a lot of functionality is missing from XVim2 [in this thread](https://github.com/XVimProject/XVim/issues/1074): what in particular? I've added back most of the original functions, and I, or other contributors, should find it quite easy to complete the work (although block mode might prove the most tricky).

Did the original XVim have many missing features for you, or just the current iteration of XVim2?

re: the NeoVim solution: I too think it would be the technically superior solution, and I think Apple might do something like that (next stage in using external processes to help in text editing).

However, I think a lot of advantages come from being able to hook directly into an IDE. Quite a lot of NeoVim is about streaming to a 'dumb' terminal, and providing lots of functionality in the back-end. That functionality will be less useful in a 'fat client' like Xcode.

The big exception is full support for scripting, though. Even there, NeoVim prefers a different script language, but provides a compatibility layer for VimScript...a PyObjC bridge in XVim is possible, if we don't bother about VimScript.

**Comment by antmd** [comment]
P.S., for the missing features, please raise them as separate issues when you have a moment.

**Comment by squarefrog** [comment]
Ignore what I said in the previous thread, as the missing/incomplete features were from the two plugins battling each other, which is now resolved. I hadn't found many Vim functions that were missing in XVim, but I'll admit I don't dig too much below the surface.

Thanks for the notes on NeoVim, I had just assumed it was a text processor backend to handle the movement, macros etc. Re-reading the original thread, it certainly seems like there are significant trade-offs such as losing code completion and syntax highlighting. Perhaps naively, I had assumed that you simply forwarded on keystrokes, and NeoVim returned the current file text to just update the current Xcode view.
