### ISSUE TITLE
a inserts cursor before last character at the end of a line

### ISSUE THREAD

**Issue by gh123man** [XVimProject/XVim2#50]
When using `a` or `S-a` the cursor is not placed at the very end of the line, but instead before the last character.

**Comment by MavEtJu** [comment]
So does "C" (change to the end of line).

**Comment by limitLiu** [comment]
You can use "2ae2aceb6ab5ea186a066d0b5e9ca18372059c1e", it is ok.

**Comment by antmd** [comment]
This is now fixed. Please pull `master` and try again.

**Comment by MavEtJu** [comment]
Confirmed, thanks!
