### ISSUE TITLE
Thank you for releasing XVim2

### ISSUE THREAD

**Issue by liaa** [XVimProject/XVim2#54]
Have been using Xcode 9 without XVim for a while and feel very inconvenient. Finally, it's here, Thank you

**Comment by Munk801** [comment]
Ammend to this, thanks for all the hard work in getting this out!  I felt the same way with all sorts of regret of updating to XCode 9.  Long live XVim.

**Comment by antmd** [comment]
@liaa @Munk801  Thanks. I'm happy that you find XVim2 useful.
