### ISSUE TITLE
Visual/Insert marker covers status line

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim2#56]
While trying to replace text in a block `-- VISUAL LINE --` should be hidden, while the user types.

Steps to reproduce:

1. Select a line using `shift+v`
1. Press `:` to start entering search/replace
1. Notice any text entered cannot be read due to the `-- VISUAL LINE --` descriptor

**Comment by antmd** [comment]
@squarefrog please pull, and checkout `develop` branch to try the fix. Thanks.

**Comment by antmd** [comment]
@squarefrog thanks for the crash report. I just pushed to `develop`. Please try again.

**Comment by squarefrog** [comment]
Confirmed fixed in e182afba52c68ee5f3cd8e6cb05c4691c5e42e22  thanks @antmd  🎉

**Comment by antmd** [comment]
@squarefrog  I committed a critical bug fix to `develop` yesterday. Please pull this version when you have a moment. The bug would cause crashes every now and again.

**Comment by squarefrog** [comment]
@antmd I had noticed a crash but I was on a sprint at work so forgot to post a report. Will pull first thing Monday, thanks for the heads up.
