### ISSUE TITLE
i wanna know how to update the plug-in

### ISSUE THREAD

**Issue by quanxin** [XVimProject/XVim2#57]
there has been many updates since i install XVim2, the problem is i'm not very sure i've kept these updates.
so i want to make sure whether should i just Git Pull and perform ‘make’ in terminal or i need to do something else?
thank you so much.

**Comment by sendyhalim** [comment]
@quanxin I've been spamming `make uninstall` and then `make` every time I update the repo (`git pull`) on master branch and everything seems to be okay :running_man:

**Comment by quanxin** [comment]
@sendyhalim thank you very much😀
