### ISSUE TITLE
don't know how to go into vim mode after installation

### ISSUE THREAD

**Issue by abbood** [XVimProject/XVim2#61]
I followed the installation instructions, loaded the bundles and restarted xcode and everything.

but once I'm in xcode.. pressing escape doesn't give me the usual vim prompt.. what am I doing wrong?

**Comment by ralph-e-boy** [comment]
@abbood did you codesign xcode as per https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md ?

**Comment by vi4m** [comment]
Is this really required for Xcode 9 ? I was thinking that new XVim is built with the official API in mind?

**Comment by ralph-e-boy** [comment]
signing is required, Xvim2 uses swizzling ->  https://github.com/XVimProject/XVim2/blob/b6eb999d96eb33e9c8a488a071aa441e6f189fb3/XVim2/Xcode/IDEPegasusSourceEditor/_TtC22IDEPegasusSourceEditor20SourceCodeEditorView.m#L29 
this thread has some info on implementation  https://github.com/XVimProject/XVim/issues/1074

**Comment by abbood** [comment]
this is weird.. i followed those steps. and it worked fine. but now that that i relaunched xcode after a while.. it's not working any more :(

**Comment by abbood** [comment]
this is what i did
```
$ security find-certificate
keychain: "/Users/***/Library/Keychains/login.keychain-db"
version: 512
class: 0x80001000
attributes:
    "alis"<blob>="iPhone Developer: abdullah.bakhach@gmail.com (7gwxb5ja52)"
  ...
abdullah@Abdullahs-MacBook-Pro-2:~$ sudo codesign -f -s "iPhone Developer: abdullah.bakhach@gmail.com (7gwxb5ja52)" /Applications/Xcode.app
Password:
/Applications/Xcode.app: replacing existing signature
```

**Comment by jcarpent** [comment]
@abbood Did you solve your issue?

**Comment by abbood** [comment]
@jcarpent  no it keeps on coming back again and again ..

**Comment by pebble8888** [comment]
I close it because of old installation issue.
