### ISSUE TITLE
make build failure

### ISSUE THREAD

**Issue by seratonic** [XVimProject/XVim2#62]
I cloned XVim2 a few minutes ago.  When I ran make (from tcsh) I got the following build errors:

-c /Users/...me.../projects/xvim2/XVim2/XVim2/XVim/XVimHistoryHandler.m -o /Users/...me.../projects/xvim2/XVim2/build/XVim2.build/Release/XVim2.build/Objects-normal/i386/XVimHistoryHandler.o
/Users/me/GoogleDrive/projects/xvim2/XVim2/XVim2/XVim/XVimHistoryHandler.m:12:21: error: instance variables may not be
      placed in class extension
    NSMutableArray* _history;
                    ^
/Users/me/GoogleDrive/projects/xvim2/XVim2/XVim2/XVim/XVimHistoryHandler.m:21:9: error: use of undeclared identifier
      '_history'
        _history = [[NSMutableArray alloc] init];
        ^
/Users/me/GoogleDrive/projects/xvim2/XVim2/XVim2/XVim/XVimHistoryHandler.m:26:38: error: use of undeclared identifier
      '_history'
- (void)addEntry:(NSString*)entry { [_history insertObject:entry atIndex:0]; }
                                     ^
/Users/me/GoogleDrive/projects/xvim2/XVim2/XVim2/XVim/XVimHistoryHandler.m:32:25: error: use of undeclared identifier
      '_history'
    for (NSString* s in _history) {
                        ^
4 errors generated.

Please advise.

Thanks!!

**Comment by seratonic** [comment]
When I build within Xcode 9.0.1 (9A1004) the build succeeds.  When I restart it asks if I want to load the plug-in.  I respond Yes.  Now, with Xcode running on any project I don't see any vim emulation in the editor.

So a couple of questions:  is building within Xcode the preferred method or, per README.md, is "make" the preferred installation method ?

Second, in older versions of xvim I would just build in Xcode, restart and I'd be up and running.  Are there any settings / config steps to enable vi emulation ?

**Comment by seratonic** [comment]
Ok, so looks like the default make target is release.  When I do a "make debug" all works as hoped.  I haven't seen any performance degradation from the debug build but it would be nice if the release target was working.

Please scratch the second question in previous post, my apologies all, I needed to re-sign Xcode since my version 9.0 update.

Thank you.

**Comment by pebble8888** [comment]
already fixed
