### ISSUE TITLE
Status line feedback when in INSERT/NORMAL mode

### ISSUE THREAD

**Issue by omartin** [XVimProject/XVim2#7]
I'm not seeing the current mode in the status line, maybe I'm missing an option ?

**Comment by antmd** [comment]
The status line isn't there yet. The cursor shows the current 'major' mode (block = normal, bar = insert). I'd like to add an option for the command line to auto-hide, and show only when needed. If there's some info that is really important to show all the time, perhaps there's a more 'modern' way of showing it in Xcode. Perhaps not. Is it just the mode that you need to see?

**Comment by omartin** [comment]
I agree it's cluttering the view and a bit old fashioned but somehow I'm used to have a visual feedback for the current mode.

**Comment by omartin** [comment]
The VIM plugin in IntelliJ (IdeaVim) hides the status line by default and only shows it when entering commands in normal mode, maybe we can have this for behaviour first

**Comment by omartin** [comment]
Fixed in master
