### ISSUE TITLE
XVim2 stopped working after the latest xcode update?

### ISSUE THREAD

**Issue by a-eid** [XVimProject/XVim2#72]
Now I know I shouldn't update xcode frequently!

I also reinstalled , asked if I'm sure I pressed (y) , also have loaded the bundle .

but it does not work.

**Comment by wdcew** [comment]
if Xocde version is 9.2Beta, your should update UUID

**Comment by Anyewuya** [comment]
Maybe you didnot resign xcode

**Comment by a-eid** [comment]
@wdcew I was not using a beta version. 
@Anyewuya do I have to sign xcode after updating to 9.1 , ( xvim2 was working with xcode 9.0 )
