### ISSUE TITLE
[Question] is there a better way to cancel the auto completion popup?

### ISSUE THREAD

**Issue by squarefrog** [XVimProject/XVim2#73]
I've notice while writing code, sometimes I wan't to cancel Xcodes auto completion so I can hit return for the next line.

Without Xvim, I'd just hit `Esc`, but while using Xvim I have to press `Esc`, then `o` to open a new line. This isn't a massive issue usually, but sometimes I forget!

**Comment by wdcew** [comment]
you can try "control +  space" keyboard shortcut，it wii show/hide completion

**Comment by squarefrog** [comment]
Yes that does the trick, thanks 👍
