### ISSUE TITLE
Problems pressing j and k.

### ISSUE THREAD

**Issue by yangj123** [XVimProject/XVim2#74]
Xcode Version 9.1 (9B55)

Yesterday I installed Xvim2. But if I pressed j or k, the cursor always jumped to the first line of the page. Other keys work fine.

This is very strange. I have uninstalled Xvim2 and reinstalled it several times, and this problem still exists.

I tried XVim2 at my laptop and iMac (with the same Xcode version) and found the same problem.

I also tried the develop branch, and the problem is the same.

How can I fix this problem? Thanks.

**Comment by yangj123** [comment]
I also tried the develop branch, and the problem is the same.

**Comment by wdcew** [comment]
if you map "j" to "gj" in .xvimrc, you can try delete it.

**Comment by abhisood** [comment]
@wdcew - That was it! Removed the mapping and it works as expected now. Thanks!

**Comment by yangj123** [comment]
@wdcew Thanks a lot!!!
