### ISSUE TITLE
Paste from the system cliboard at end of file then press Esc crashes Xcode 9.1

### ISSUE THREAD

**Issue by Philosophix** [XVimProject/XVim2#76]
If I copy text (swift code) from the Notes-application and paste it at the end of the file and try to use Esc to exit insert mode, Xcode 9.1 crashes. When I then tried to copy text to the system clipboard from within Xcode, everything seems fine. It only seems to crash when pasting text copied from another app (although I haven't tried any other apps then Notes). Rtf-issue??

**Comment by solidcell** [comment]
Yea, this one bites me a lot. It causes Xcode to crash for me at least a couple times a day, just due to this one issue.

**Comment by pebble8888** [comment]
The issue is fixed on master branch and also develop branch.
