### ISSUE TITLE
Delete without copy

### ISSUE THREAD

**Issue by ober01** [XVimProject/XVim2#8]
In my .xvimrc file : 

> set clipboard=unnamed
> nmap x "_x

result: 'x' command removes symbol with adding to the clipboard
expected result: 'x' command removes symbol without adding to the clipboard.

**Comment by antmd** [comment]
Hi, the commit to read the xvimrc was about three hours ago. Are you using that version? If not, please pull, and try again.

**Comment by ober01** [comment]
Yes, I use the last version.
.xvimrc file works great  

this line works `set clipboard=unnamed` (xvim clipboard and osx clipboard synchronize).
this line doesn't work `nmap x "_x` (this line override 'x' keyboard, it must remove the character without adding to clipboard)

**Comment by ober01** [comment]
Works in the last version
