### ISSUE TITLE
feature request: zt and zb

### ISSUE THREAD

**Issue by CallumHoward** [XVimProject/XVim2#85]
`zz` centers the screen on the cursor, this works in XVim2. The related commands `zt` and `zb` move the screen so the cursor is at the top and bottom respectively. These two are not yet implemented.

I would like to request this feature, thanks.

**Comment by pebble8888** [comment]
I implemented zt and zb.
The feature is a little bit unstable but you can use it.

**Comment by pebble8888** [comment]
zt, zb is implemented in `develop` branch.

d02a9ae

Please check it.

**Comment by pebble8888** [comment]
No response. close this.
