### ISSUE TITLE
Didn't work for 9.2 beta(9C34b)

### ISSUE THREAD

**Issue by Insofan** [XVimProject/XVim2#86]

**Comment by jspavlick** [comment]
I've been so far unsuccessful getting it to work for Xcode 9.2

**Comment by harryworld** [comment]
Xcode 9.2 official is out now

**Comment by Crux-One** [comment]
Waiting a patch for 9.2. I appreciate that.

**Comment by harryworld** [comment]
There are couple PRs now, you can pull them to continue working for instance #89 #90 😉

**Comment by kylestew** [comment]
These changes don't seem to work for 9.2 (9C40b). What am I missing? Maybe another UUID for the production Xcode version?
Need my Vim fix :)

**Comment by harryworld** [comment]
@kylestew Try the followings:

0. CodeSign Xcode
1. Pull from one of the PRs branches
2. `make uninstall` to clear you had
3. `make` to build XVim2 again
4. Restart Xcode

**Comment by jeromecovington** [comment]
Can you explain (to an xcode noob) how to codesign xcode?

I am codesigning the plugin itself with:
```
$ /usr/bin/codesign --force --sign - --timestamp=none /Users/jcovingt/XVim2/build/Release/XVim2.xcplugin
```

But, I am not seeing the vim bindings working in the playground I have open.

**Comment by harryworld** [comment]
@jeromecovington You should codesign Xcode

Run the command like this with your own certificate, changed [certificate name] to your own.

```
sudo codesign -f -s "[certificate name]" /Applications/Xcode.app
```

**Comment by jeromecovington** [comment]
Thanks, I'm sorry if I'm taking up space on this thread, but when I decide to create a certificate from within Xcode, I get this list of possibilities and am not sure which one I need. If no-one wants to answer in this context I can go to stackexchange or the like, I'd totally understand.
![image](https://user-images.githubusercontent.com/486493/36035128-0666b404-0d84-11e8-817a-898cd5e71bb2.png)

**Comment by jeromecovington** [comment]
NM, I found this documentation, thanks. https://github.com/XVimProject/XVim2/blob/master/SIGNING_Xcode.md
