### ISSUE TITLE
Don't work for Xcode9.2 release.

### ISSUE THREAD

**Issue by menq** [XVimProject/XVim2#97]
try use the PRs.
still not work.

**Comment by qhua948** [comment]
Have you made sure you have codesigned your xcode?

**Comment by heefan** [comment]
check out this, #86 
It works for me. Do remember code sign first and install. 
My dev environment is the followings,
Xcode 9.2 (9C40b), and macOS 10.13.2 (17C88).

**Comment by menq** [comment]
@qhua948  @heefan  
Thanks, it seems that xcode need to codesign everytime after its updates
