### ISSUE TITLE
shiftwidth broken (">>")

### ISSUE THREAD

**Issue by patniemeyer** [XVimProject/XVim2#99]
">>" seems to double indent (twice the shift width).  In fact hitting undo removes one of the indents... so that is a workaround :)

**Comment by kmsheng** [comment]
I've experienced this issue, too.

**Comment by pebble8888** [comment]
It's fixed in develop branch already.
451aa93d758d1241c876b692a6837555891e297d

**Comment by patniemeyer** [comment]
Awesome!  Thanks!

**Comment by jstarschuyler** [comment]
I just installed the latest version of XVim2 after upgrading to XCode 9.2 and it is ignoring my `shiftwidth` configurations.

The project I work in uses 3 space tabs but I get 4 on all `shiftwidth` commands

I have tried these two configurations in my `~/.xvimrc` (and I restarted XCode after each change)
```
set shiftwidth=3
```
and
```
au FileType cpp setl sw=3 sts=3 et 
```

Setting `shiftwidth` in command mode also does not work.

**Comment by pebble8888** [comment]
fixed.

@jstarschuyler 
`set shift-width` is not supported.
